import { deepFreeze } from "../immutability";
import { confidenceForBand } from "../catalogue/relationship-helpers";
import { resolveCanonicalScopeId } from "../catalogue/normalisation";
import { SCOPE_DISCOVERY_CONTRACT_VERSION } from "../version";
import type {
  EvidenceItem,
  ScopeDiscoverySuggestion,
} from "../types";
import type {
  ProviderRawOutput,
  ScopeDiscoveryProviderInput,
} from "./types";
import { SCOPE_DISCOVERY_PROMPT_VERSION } from "./version";

function deterministicUuid(seed: string): string {
  let h1 = 2166136261;
  let h2 = 2166136261 ^ 0xabcdef;
  for (let i = 0; i < seed.length; i += 1) {
    const c = seed.charCodeAt(i);
    h1 ^= c;
    h1 = Math.imul(h1, 16777619);
    h2 ^= c + i;
    h2 = Math.imul(h2, 16777619);
  }
  const hex = (n: number, len: number) =>
    (n >>> 0).toString(16).padStart(len, "0").slice(-len);
  const a = hex(h1, 8);
  const b = hex(h1 ^ h2, 4);
  const c = `4${hex(h2, 3)}`;
  const d = `8${hex(h1 ^ 0x1234, 3)}`;
  const e = `${hex(h2 ^ 0x5678, 4)}${hex(h1 ^ h2 ^ 0x9abc, 8)}`.slice(0, 12);
  return `${a}-${b}-${c}-${d}-${e}`;
}

function mapEvidenceRef(
  ref: string,
  input: ScopeDiscoveryProviderInput,
  createdAt: string
): EvidenceItem {
  if (ref === "brief:project") {
    return {
      sourceType: "PROJECT_BRIEF_TEXT",
      sourceId: "brief",
      excerptOrValue: input.projectBrief.slice(0, 240),
      relevance: "primary",
      timestamp: createdAt,
      provenance: "ai",
      userAuthored: false,
      authoritative: false,
    };
  }
  if (ref.startsWith("note:")) {
    const noteId = ref.slice("note:".length);
    const note = input.selectedSiteNotes.find((n) => n.noteId === noteId);
    return {
      sourceType: "SITE_NOTE",
      sourceId: noteId,
      excerptOrValue: (note?.content ?? "").slice(0, 240),
      relevance: "supporting",
      timestamp: createdAt,
      provenance: "ai",
      userAuthored: true,
      authoritative: false,
    };
  }
  if (ref.startsWith("fact:")) {
    const key = ref.slice("fact:".length);
    const fact = input.relevantFacts.find((f) => f.key === key);
    return {
      sourceType: "USER_FACT",
      sourceId: key,
      excerptOrValue: fact ? String(fact.value) : key,
      relevance: "supporting",
      timestamp: createdAt,
      provenance: "user",
      userAuthored: true,
      authoritative: true,
    };
  }
  if (ref.startsWith("constraint:")) {
    const key = ref.slice("constraint:".length);
    const constraint = input.relevantConstraints.find((c) => c.key === key);
    return {
      sourceType: "CONSTRAINT",
      sourceId: key,
      excerptOrValue: constraint ? String(constraint.value) : key,
      relevance: "supporting",
      timestamp: createdAt,
      provenance: "user",
      userAuthored: true,
      authoritative: true,
    };
  }
  if (ref.startsWith("work-area:")) {
    const id = ref.slice("work-area:".length);
    const wa = input.acceptedWorkAreas.find((w) => w.workAreaId === id);
    return {
      sourceType: "EXISTING_WORK_AREA",
      sourceId: id,
      excerptOrValue: wa?.type ?? id,
      relevance: "supporting",
      timestamp: createdAt,
      provenance: "user",
      userAuthored: true,
      authoritative: true,
    };
  }
  if (ref.startsWith("rule:")) {
    return {
      sourceType: "DETERMINISTIC_RULE",
      sourceId: ref.slice("rule:".length),
      excerptOrValue: ref,
      relevance: "supporting",
      timestamp: createdAt,
      provenance: "deterministic_rule",
      userAuthored: false,
      authoritative: false,
    };
  }
  return {
    sourceType: "PROJECT_BRIEF_TEXT",
    sourceId: ref,
    excerptOrValue: ref,
    relevance: "supporting",
    timestamp: createdAt,
    provenance: "ai",
    userAuthored: false,
    authoritative: false,
  };
}

/**
 * Map validated provider output into Stage 3.1B.1 suggestions.
 * IDs are generated by Quotr — model-supplied IDs are never trusted.
 * Status is always PROPOSED. No merge with deterministic suggestions here.
 */
export function mapOutputToSuggestions(params: {
  readonly output: ProviderRawOutput;
  readonly input: ScopeDiscoveryProviderInput;
  readonly model: string;
  readonly createdAt?: string;
}): readonly ScopeDiscoverySuggestion[] {
  const createdAt = params.createdAt ?? new Date().toISOString();
  const suggestions: ScopeDiscoverySuggestion[] = [];

  for (const candidate of params.output.candidates) {
    const scope =
      resolveCanonicalScopeId(candidate.proposedWorkAreaType) ??
      candidate.proposedWorkAreaType;

    let relatedWorkAreaId: string | null = null;
    if (candidate.relatedWorkAreaReference) {
      const raw = candidate.relatedWorkAreaReference.replace(/^work-area:/, "");
      relatedWorkAreaId = raw;
    }

    const evidence = candidate.evidenceReferences.map((ref) =>
      mapEvidenceRef(ref, params.input, createdAt)
    );

    // Dedupe evidence
    const seen = new Set<string>();
    const uniqueEvidence: EvidenceItem[] = [];
    for (const item of evidence) {
      const key = `${item.sourceType}|${item.sourceId}|${item.relevance}`;
      if (seen.has(key)) continue;
      seen.add(key);
      uniqueEvidence.push(item);
    }

    const suggestionId = deterministicUuid(
      `${params.input.projectId}|${params.input.analysisRunId}|${candidate.suggestionKind}|${scope}|${candidate.rationaleCode}`
    );

    suggestions.push(
      deepFreeze({
        suggestionId,
        projectId: params.input.projectId,
        orgId: params.input.orgId,
        analysisRunId: params.input.analysisRunId,
        suggestionKind: candidate.suggestionKind,
        proposedWorkAreaType: scope,
        proposedTitle: candidate.proposedTitle,
        proposedDescription: candidate.proposedDescription,
        relatedWorkAreaId,
        parentSuggestionId: null,
        confidence: confidenceForBand(candidate.confidenceBand),
        confidenceBand: candidate.confidenceBand,
        evidence: uniqueEvidence,
        rationaleKey: candidate.rationaleCode,
        sourceSnapshot: params.input.sourceSnapshot,
        dependencyReferences: candidate.dependencyReferences,
        conflictReferences: candidate.conflictReferences,
        missingInformation: candidate.missingInformation,
        status: "PROPOSED",
        decision: null,
        contractVersion: SCOPE_DISCOVERY_CONTRACT_VERSION,
        providerMetadata: {
          provider: "anthropic",
          model: params.model,
          requestId: null,
          promptContractVersion: SCOPE_DISCOVERY_PROMPT_VERSION,
        },
        createdAt,
        updatedAt: createdAt,
        staleReason: null,
        supersededBySuggestionId: null,
        failureCode: null,
        failureMessage: null,
        catalogueEdgeId: null,
        origin: "ai",
      })
    );
  }

  return deepFreeze(suggestions);
}
