/**
 * Stage 3.2.1 — MVP question registry.
 *
 * Domains: project/site logistics, demolition/reno risk, Deck/Bathroom/Fitout packs.
 * No taxonomy expansion beyond current CORE constraint keys (D4).
 */

import { INTERVIEW_REGISTRY_VERSION } from "@/lib/builder-interview/types";
import type { RegistryQuestionDef } from "@/lib/builder-interview/types";

const V = INTERVIEW_REGISTRY_VERSION;

/** Project-wide site / logistics (CORE constraints). */
const SITE_LOGISTICS: RegistryQuestionDef[] = [
  {
    questionKey: "interview.site.site_access",
    version: V,
    domain: "SITE_ACCESS",
    scope: "PROJECT",
    writeTarget: "CONSTRAINT",
    targetKey: "site_access",
    semanticTopic: "site.access",
    question: "How difficult is site access?",
    inputType: "select",
    options: ["Easy", "Moderate", "Difficult", "Very poor"],
    priority: "P0",
    askPolicy: "ASK",
    reasonForAsking: "Access difficulty materially changes labour and logistics.",
    impact: { estimate: "labour", scope: "none", confidence: "high" },
    answerability: "ON_SITE",
    triggerRuleIds: ["has_confirmed_work_areas"],
    ownedBy: "INTERVIEW",
    registryOrder: 10,
  },
  {
    questionKey: "interview.site.material_carry_distance",
    version: V,
    domain: "LOGISTICS",
    scope: "PROJECT",
    writeTarget: "CONSTRAINT",
    targetKey: "material_carry_distance",
    semanticTopic: "site.carry",
    question: "Distance from material drop-off or waste carting?",
    inputType: "select",
    options: ["< 10m", "10–30m", "> 30m", "Not sure"],
    priority: "P0",
    askPolicy: "ASK",
    reasonForAsking: "Carry distance affects labour and waste handling.",
    impact: { estimate: "labour", scope: "none", confidence: "high" },
    answerability: "ON_SITE",
    triggerRuleIds: ["has_confirmed_work_areas"],
    ownedBy: "INTERVIEW",
    registryOrder: 20,
  },
  {
    questionKey: "interview.site.floor_level",
    version: V,
    domain: "SITE_ACCESS",
    scope: "PROJECT",
    writeTarget: "CONSTRAINT",
    targetKey: "floor_level",
    semanticTopic: "site.floor_level",
    question: "What floor level are works on?",
    inputType: "select",
    options: ["Ground", "Upper floor", "Basement", "Not sure"],
    priority: "P1",
    askPolicy: "ASK",
    reasonForAsking: "Floor level changes vertical logistics and risk.",
    impact: { estimate: "labour", scope: "low", confidence: "medium" },
    answerability: "ON_SITE",
    triggerRuleIds: ["has_confirmed_work_areas"],
    ownedBy: "INTERVIEW",
    registryOrder: 30,
  },
  {
    questionKey: "interview.site.occupied_site",
    version: V,
    domain: "LOGISTICS",
    scope: "PROJECT",
    writeTarget: "CONSTRAINT",
    targetKey: "occupied_site",
    semanticTopic: "site.occupied",
    question: "Is the site occupied during works?",
    inputType: "boolean",
    options: ["Yes", "No", "Not sure"],
    priority: "P1",
    askPolicy: "ASK",
    reasonForAsking: "Occupied sites change protection, hours, and productivity.",
    impact: { estimate: "labour", scope: "low", confidence: "high" },
    answerability: "ON_SITE",
    triggerRuleIds: ["has_confirmed_work_areas"],
    ownedBy: "INTERVIEW",
    registryOrder: 40,
  },
  {
    questionKey: "interview.site.working_hours",
    version: V,
    domain: "LOGISTICS",
    scope: "PROJECT",
    writeTarget: "CONSTRAINT",
    targetKey: "working_hours",
    semanticTopic: "site.working_hours",
    question: "Are there working-hour restrictions?",
    inputType: "boolean",
    options: ["No", "Yes", "Not sure"],
    priority: "P1",
    askPolicy: "ASK",
    reasonForAsking: "Restricted hours affect programme and labour productivity.",
    impact: { estimate: "labour", scope: "none", confidence: "medium" },
    answerability: "ON_SITE",
    triggerRuleIds: ["has_confirmed_work_areas"],
    ownedBy: "INTERVIEW",
    registryOrder: 50,
  },
  {
    questionKey: "interview.site.parking_loading",
    version: V,
    domain: "LOGISTICS",
    scope: "PROJECT",
    writeTarget: "CONSTRAINT",
    targetKey: "parking_loading",
    semanticTopic: "site.parking_loading",
    question: "Is parking or loading available on site?",
    inputType: "select",
    options: ["Easy", "Moderate", "Poor", "Not sure"],
    priority: "P2",
    askPolicy: "ASK",
    reasonForAsking: "Loading conditions affect material handling time.",
    impact: { estimate: "labour", scope: "none", confidence: "low" },
    answerability: "ON_SITE",
    triggerRuleIds: ["has_confirmed_work_areas"],
    ownedBy: "INTERVIEW",
    registryOrder: 60,
  },
];

/** Demolition / renovation risk (project constraint keys + WA overrides). */
const DEMO_RENO_RISK: RegistryQuestionDef[] = [
  {
    questionKey: "interview.risk.hazardous_materials",
    version: V,
    domain: "COMPLIANCE_RISK",
    scope: "PROJECT",
    writeTarget: "CONSTRAINT",
    targetKey: "hazardous_materials_risk",
    semanticTopic: "risk.hazmat",
    question: "Is there asbestos or hazardous materials risk?",
    inputType: "boolean",
    options: ["Yes", "No", "Not sure"],
    priority: "P1",
    askPolicy: "ASK",
    reasonForAsking: "Hazmat risk changes method, cost, and programme.",
    impact: { estimate: "risk", scope: "medium", confidence: "high" },
    answerability: "REQUIRES_EXPERT",
    triggerRuleIds: ["has_reno_or_demolition"],
    ownedBy: "INTERVIEW",
    registryOrder: 100,
  },
  {
    questionKey: "interview.risk.services_isolated",
    version: V,
    domain: "COMPLIANCE_RISK",
    scope: "PROJECT",
    writeTarget: "CONSTRAINT",
    targetKey: "services_isolated",
    semanticTopic: "risk.services",
    question: "Are services isolated before strip-out / demolition?",
    inputType: "boolean",
    options: ["Yes", "No", "Not sure"],
    priority: "P1",
    askPolicy: "ASK",
    reasonForAsking: "Live services create safety and delay risk on strip-out.",
    impact: { estimate: "risk", scope: "low", confidence: "high" },
    answerability: "ON_SITE",
    triggerRuleIds: ["has_demolition_wa"],
    ownedBy: "INTERVIEW",
    registryOrder: 110,
  },
  {
    questionKey: "interview.wa.demolition.salvage_required",
    version: V,
    domain: "EXISTING_CONDITIONS",
    scope: "WORK_AREA",
    workAreaType: "demolition",
    writeTarget: "FACT",
    targetKey: "demolition.salvage_required",
    semanticTopic: "demo.salvage",
    question: "Is salvage of materials required?",
    inputType: "boolean",
    options: ["Yes", "No", "Not sure"],
    priority: "P2",
    askPolicy: "ASK",
    reasonForAsking: "Salvage increases labour and handling time.",
    impact: { estimate: "labour", scope: "low", confidence: "medium" },
    answerability: "ON_SITE",
    triggerRuleIds: ["has_demolition_wa", "work_area_type_matches"],
    ownedBy: "INTERVIEW",
    registryOrder: 120,
  },
  {
    questionKey: "interview.wa.demolition.access_override",
    version: V,
    domain: "SITE_ACCESS",
    scope: "WORK_AREA",
    workAreaType: "demolition",
    writeTarget: "FACT",
    targetKey: "demolition.access",
    semanticTopic: "site.access",
    question: "Does demolition access differ from general site access?",
    inputType: "select",
    options: ["Easy", "Moderate", "Poor", "Very poor", "Not sure"],
    priority: "P1",
    askPolicy: "ASK",
    reasonForAsking:
      "Only when demolition floor/access differs from project-wide site access.",
    impact: { estimate: "labour", scope: "none", confidence: "medium" },
    answerability: "ON_SITE",
    triggerRuleIds: ["has_demolition_wa", "work_area_type_matches"],
    requiresLocalOverride: true,
    ownedBy: "INTERVIEW",
    registryOrder: 130,
  },
];

/**
 * WA access clones — present only to prove project-wide suppression / override.
 * Normally suppressed when project site.access is known and override not met.
 */
const WA_ACCESS_CLONES: RegistryQuestionDef[] = [
  "demolition",
  "internal_walls",
  "ceilings",
  "doors",
  "flooring",
  "painting",
  "plastering",
  "deck",
  "bathroom",
].map((waType, index) => ({
  questionKey: `interview.wa.${waType}.access_clone`,
  version: V,
  domain: "SITE_ACCESS" as const,
  scope: "WORK_AREA" as const,
  workAreaType: waType,
  writeTarget: "FACT" as const,
  targetKey: `${waType}.access`,
  semanticTopic: "site.access" as const,
  question: `How difficult is access for ${waType.replace("_", " ")}?`,
  inputType: "select" as const,
  options: ["Easy", "Moderate", "Poor", "Very poor", "Not sure"],
  priority: "P2" as const,
  askPolicy: "ASK" as const,
  reasonForAsking:
    "WA access clone — suppressed by project site_access unless override trigger.",
  impact: {
    estimate: "labour" as const,
    scope: "none" as const,
    confidence: "low" as const,
  },
  answerability: "ON_SITE" as const,
  triggerRuleIds: ["work_area_type_matches"] as const,
  requiresLocalOverride: true,
  ownedBy: "INTERVIEW" as const,
  registryOrder: 200 + index,
}));

const WA_CARRY_CLONES: RegistryQuestionDef[] = [
  {
    questionKey: "interview.wa.demolition.carting_clone",
    version: V,
    domain: "LOGISTICS",
    scope: "WORK_AREA",
    workAreaType: "demolition",
    writeTarget: "FACT",
    targetKey: "demolition.carting_distance_m",
    semanticTopic: "site.carry",
    question: "Approximate carting distance for demolition waste (m)?",
    inputType: "number",
    priority: "P2",
    askPolicy: "ASK",
    reasonForAsking:
      "WA carry clone — suppressed by project material_carry_distance unless override.",
    impact: { estimate: "labour", scope: "none", confidence: "low" },
    answerability: "REQUIRES_MEASUREMENT",
    triggerRuleIds: ["has_demolition_wa", "work_area_type_matches"],
    requiresLocalOverride: true,
    ownedBy: "INTERVIEW",
    registryOrder: 220,
  },
];

/** DEFER — Scope Details owns these (must never ASK). */
const SCOPE_DETAILS_DEFER: RegistryQuestionDef[] = [
  {
    questionKey: "interview.defer.internal_walls.framing_type",
    version: V,
    domain: "SPECIFICATION_CONTEXT",
    scope: "WORK_AREA",
    workAreaType: "internal_walls",
    writeTarget: "FACT",
    targetKey: "internal_walls.framing_type",
    semanticTopic: "details.component",
    question: "What framing type for internal walls?",
    inputType: "select",
    priority: "P3",
    askPolicy: "DEFER",
    reasonForAsking: "Owned by Scope Details.",
    impact: { estimate: "material", scope: "low", confidence: "low" },
    answerability: "ON_SITE",
    triggerRuleIds: ["work_area_type_matches"],
    ownedBy: "SCOPE_DETAILS",
    registryOrder: 900,
  },
  {
    questionKey: "interview.defer.ceilings.system",
    version: V,
    domain: "SPECIFICATION_CONTEXT",
    scope: "WORK_AREA",
    workAreaType: "ceilings",
    writeTarget: "FACT",
    targetKey: "ceilings.system",
    semanticTopic: "details.component",
    question: "What ceiling system?",
    inputType: "select",
    priority: "P3",
    askPolicy: "DEFER",
    reasonForAsking: "Owned by Scope Details.",
    impact: { estimate: "material", scope: "low", confidence: "low" },
    answerability: "ON_SITE",
    triggerRuleIds: ["work_area_type_matches"],
    ownedBy: "SCOPE_DETAILS",
    registryOrder: 901,
  },
  {
    questionKey: "interview.defer.doors.count",
    version: V,
    domain: "DIMENSIONS",
    scope: "WORK_AREA",
    workAreaType: "doors",
    writeTarget: "FACT",
    targetKey: "doors.count",
    semanticTopic: "details.component",
    question: "How many doors?",
    inputType: "number",
    priority: "P3",
    askPolicy: "DEFER",
    reasonForAsking: "Owned by Scope Details.",
    impact: { estimate: "quantity", scope: "low", confidence: "low" },
    answerability: "ON_SITE",
    triggerRuleIds: ["work_area_type_matches"],
    ownedBy: "SCOPE_DETAILS",
    registryOrder: 902,
  },
  {
    questionKey: "interview.defer.painting.coat_count",
    version: V,
    domain: "SPECIFICATION_CONTEXT",
    scope: "WORK_AREA",
    workAreaType: "painting",
    writeTarget: "FACT",
    targetKey: "painting.coat_count",
    semanticTopic: "details.component",
    question: "How many paint coats?",
    inputType: "number",
    priority: "P3",
    askPolicy: "DEFER",
    reasonForAsking: "Owned by Scope Details.",
    impact: { estimate: "material", scope: "none", confidence: "low" },
    answerability: "ON_SITE",
    triggerRuleIds: ["work_area_type_matches"],
    ownedBy: "SCOPE_DETAILS",
    registryOrder: 903,
  },
  {
    questionKey: "interview.defer.plastering.finish_level",
    version: V,
    domain: "SPECIFICATION_CONTEXT",
    scope: "WORK_AREA",
    workAreaType: "plastering",
    writeTarget: "FACT",
    targetKey: "plastering.finish_level",
    semanticTopic: "details.component",
    question: "What plaster finish level?",
    inputType: "select",
    priority: "P3",
    askPolicy: "DEFER",
    reasonForAsking: "Owned by Scope Details.",
    impact: { estimate: "material", scope: "none", confidence: "low" },
    answerability: "ON_SITE",
    triggerRuleIds: ["work_area_type_matches"],
    ownedBy: "SCOPE_DETAILS",
    registryOrder: 904,
  },
  {
    questionKey: "interview.defer.bathroom.waterproofing",
    version: V,
    domain: "SPECIFICATION_CONTEXT",
    scope: "WORK_AREA",
    workAreaType: "bathroom",
    writeTarget: "FACT",
    targetKey: "bathroom.waterproofing_included",
    semanticTopic: "details.component",
    question: "Is waterproofing included?",
    inputType: "boolean",
    priority: "P2",
    askPolicy: "DEFER",
    reasonForAsking: "Owned by Scope Details.",
    impact: { estimate: "material", scope: "medium", confidence: "medium" },
    answerability: "ON_SITE",
    triggerRuleIds: ["has_bathroom_wa", "work_area_type_matches"],
    ownedBy: "SCOPE_DETAILS",
    registryOrder: 905,
  },
];

/** FLAG — Scope Review owns scope existence. */
const SCOPE_REVIEW_FLAG: RegistryQuestionDef[] = [
  {
    questionKey: "interview.flag.deck.balustrade_existence",
    version: V,
    domain: "SCOPE_CONTEXT",
    scope: "WORK_AREA",
    workAreaType: "deck",
    writeTarget: "NONE",
    targetKey: "deck.balustrade_required",
    semanticTopic: "scope.existence",
    question: "Is a balustrade required?",
    inputType: "boolean",
    priority: "P2",
    askPolicy: "FLAG",
    reasonForAsking: "Scope existence belongs to Scope Review / Details decisions.",
    impact: { estimate: "none", scope: "high", confidence: "medium" },
    answerability: "ON_SITE",
    triggerRuleIds: ["has_deck_wa", "work_area_type_matches"],
    ownedBy: "SCOPE_REVIEW",
    registryOrder: 950,
  },
  {
    questionKey: "interview.flag.fitout.fire_seismic_existence",
    version: V,
    domain: "SCOPE_CONTEXT",
    scope: "PROJECT",
    writeTarget: "NONE",
    targetKey: "fitout.fire_seismic_required",
    semanticTopic: "scope.existence",
    question: "Are fire or seismic upgrades in scope?",
    inputType: "boolean",
    priority: "P1",
    askPolicy: "FLAG",
    reasonForAsking: "Scope existence belongs to Scope Review / ISD.",
    impact: { estimate: "none", scope: "high", confidence: "high" },
    answerability: "REQUIRES_EXPERT",
    triggerRuleIds: ["has_confirmed_work_areas"],
    ownedBy: "SCOPE_REVIEW",
    registryOrder: 951,
  },
];

/** Conditional child example — salvage detail after salvage_required=true. */
const CONDITIONAL: RegistryQuestionDef[] = [
  {
    questionKey: "interview.wa.demolition.salvage_detail",
    version: V,
    domain: "EXISTING_CONDITIONS",
    scope: "WORK_AREA",
    workAreaType: "demolition",
    writeTarget: "FACT",
    targetKey: "demolition.salvage_notes",
    semanticTopic: "demo.salvage",
    question: "What materials must be salvaged?",
    inputType: "text",
    priority: "P3",
    askPolicy: "ASK",
    reasonForAsking: "Only when salvage is required.",
    impact: { estimate: "labour", scope: "low", confidence: "low" },
    answerability: "ON_SITE",
    triggerRuleIds: ["has_demolition_wa", "work_area_type_matches"],
    dependsOnQuestionKey: "interview.wa.demolition.salvage_required",
    ownedBy: "INTERVIEW",
    registryOrder: 125,
  },
];

export const INTERVIEW_QUESTION_REGISTRY: readonly RegistryQuestionDef[] = [
  ...SITE_LOGISTICS,
  ...DEMO_RENO_RISK,
  ...CONDITIONAL,
  ...WA_ACCESS_CLONES,
  ...WA_CARRY_CLONES,
  ...SCOPE_DETAILS_DEFER,
  ...SCOPE_REVIEW_FLAG,
];

export function getRegistryQuestion(
  questionKey: string
): RegistryQuestionDef | undefined {
  return INTERVIEW_QUESTION_REGISTRY.find((q) => q.questionKey === questionKey);
}

export function listRegistryByAskPolicy(
  policy: RegistryQuestionDef["askPolicy"]
): RegistryQuestionDef[] {
  return INTERVIEW_QUESTION_REGISTRY.filter((q) => q.askPolicy === policy);
}
