import type { ScopeDefinition } from "@/lib/scopes/types";

export const bathroomScope: ScopeDefinition = {
  type: "bathroom",
  label: "Bathroom renovation",
  questions: [
    {
      key: "bathroom.area_m2",
      label: "Bathroom area",
      questionText: "What is the approximate bathroom floor area?",
      inputType: "number",
      unit: "m²",
      required: true,
      priority: 10,
      factKey: "bathroom.area_m2",
      workAreaType: "bathroom",
      category: "measurement",
    },
    {
      key: "bathroom.renovation_type",
      label: "Renovation type",
      questionText: "What type of bathroom renovation is this?",
      inputType: "select",
      options: [
        "Minor refresh",
        "Standard renovation",
        "Full strip-out and rebuild",
        "Not sure",
      ],
      required: true,
      priority: 15,
      factKey: "bathroom.renovation_type",
      workAreaType: "bathroom",
      category: "scope",
    },
    {
      key: "bathroom.finish_level",
      label: "Finish level",
      questionText: "What finish level should be allowed for this bathroom?",
      inputType: "select",
      options: ["Budget", "Standard", "Premium", "Not sure"],
      required: true,
      priority: 20,
      factKey: "bathroom.finish_level",
      workAreaType: "bathroom",
      category: "finish",
    },
    {
      key: "bathroom.demolition_required",
      label: "Demolition",
      questionText: "Is demolition/strip-out included?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: true,
      priority: 30,
      factKey: "bathroom.demolition_required",
      workAreaType: "bathroom",
      category: "scope",
    },
    {
      key: "bathroom.fixtures_client_supplied",
      label: "Client-supplied fixtures",
      questionText: "Are bathroom fixtures client supplied?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: true,
      priority: 35,
      factKey: "bathroom.fixtures_client_supplied",
      workAreaType: "bathroom",
      category: "scope",
    },
    {
      key: "bathroom.fixtures_included",
      label: "Fixtures included",
      questionText: "Which fixtures are included in the contractor supply?",
      inputType: "multi_select",
      options: [
        "Toilet",
        "Shower",
        "Bath",
        "Vanity",
        "Basin",
        "Mixer/tapware",
        "Mirror/cabinet",
        "Towel rail",
        "Accessories",
        "Other",
      ],
      required: false,
      priority: 36,
      factKey: "bathroom.fixtures_included",
      workAreaType: "bathroom",
      category: "scope",
    },
    {
      key: "bathroom.waterproofing_included",
      label: "Waterproofing",
      questionText: "Is waterproofing included?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 40,
      factKey: "bathroom.waterproofing_included",
      workAreaType: "bathroom",
      category: "scope",
    },
    {
      key: "bathroom.tiling_included",
      label: "Tiling",
      questionText: "Is tiling included?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 45,
      factKey: "bathroom.tiling_included",
      workAreaType: "bathroom",
      category: "scope",
    },
    {
      key: "bathroom.floor_tiling_area_m2",
      label: "Floor tiling area",
      questionText: "Approximate floor tiling area?",
      inputType: "number",
      unit: "m²",
      required: false,
      priority: 46,
      factKey: "bathroom.floor_tiling_area_m2",
      workAreaType: "bathroom",
      category: "measurement",
    },
    {
      key: "bathroom.wall_tiling_area_m2",
      label: "Wall tiling area",
      questionText: "Approximate wall tiling area?",
      inputType: "number",
      unit: "m²",
      required: false,
      priority: 47,
      factKey: "bathroom.wall_tiling_area_m2",
      workAreaType: "bathroom",
      category: "measurement",
    },
    {
      key: "bathroom.tile_extent",
      label: "Tiling extent",
      questionText: "What tiling extent should be allowed for?",
      inputType: "select",
      options: [
        "Floor only",
        "Floor and walls",
        "Full height",
        "Splashback only",
        "Not sure",
      ],
      required: false,
      priority: 48,
      factKey: "bathroom.tile_extent",
      workAreaType: "bathroom",
      category: "scope",
    },
    {
      key: "bathroom.shower_type",
      label: "Shower type",
      questionText: "What shower type is included?",
      inputType: "select",
      options: [
        "Acrylic",
        "Tiled shower",
        "Walk-in tiled shower",
        "Shower-over-bath",
        "Not sure",
      ],
      required: false,
      priority: 49,
      factKey: "bathroom.shower_type",
      workAreaType: "bathroom",
      category: "scope",
    },
    {
      key: "bathroom.wall_tile_height",
      label: "Wall tile height",
      questionText: "What wall tiling height is required?",
      inputType: "select",
      options: [
        "Splashback only",
        "Half height",
        "Full height",
        "Wet area only",
        "Not sure",
      ],
      required: false,
      priority: 49,
      factKey: "bathroom.wall_tile_height",
      workAreaType: "bathroom",
      category: "scope",
    },
    {
      key: "bathroom.ventilation_included",
      label: "Ventilation",
      questionText: "Is an extractor fan or ventilation included?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 49,
      factKey: "bathroom.ventilation_included",
      workAreaType: "bathroom",
      category: "scope",
    },
    {
      key: "bathroom.wall_lining_included",
      label: "Wall lining",
      questionText: "Is wall lining (GIB/Aqualine) included?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 49,
      factKey: "bathroom.wall_lining_included",
      workAreaType: "bathroom",
      category: "scope",
    },
    {
      key: "bathroom.floor_prep_included",
      label: "Floor prep",
      questionText: "Is floor levelling/substrate prep included?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 49,
      factKey: "bathroom.floor_prep_included",
      workAreaType: "bathroom",
      category: "scope",
    },
    {
      key: "bathroom.access",
      label: "Access difficulty",
      questionText: "What is the site access like for this bathroom?",
      inputType: "select",
      options: ["Easy", "Moderate", "Difficult", "Not sure"],
      required: false,
      priority: 65,
      factKey: "bathroom.access",
      workAreaType: "bathroom",
      category: "risk",
    },
    {
      key: "bathroom.underfloor_heating_included",
      label: "Underfloor heating",
      questionText: "Is underfloor heating included?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 50,
      factKey: "bathroom.underfloor_heating_included",
      workAreaType: "bathroom",
      category: "allowance",
    },
    {
      key: "bathroom.plumbing_changes",
      label: "Plumbing changes",
      questionText: "What level of plumbing changes are included?",
      inputType: "select",
      options: ["None", "Minor", "Major", "Not sure"],
      required: false,
      priority: 55,
      factKey: "bathroom.plumbing_changes",
      workAreaType: "bathroom",
      category: "scope",
    },
    {
      key: "bathroom.electrical_changes",
      label: "Electrical changes",
      questionText: "What level of electrical changes are included?",
      inputType: "select",
      options: ["None", "Minor", "Major", "Not sure"],
      required: false,
      priority: 60,
      factKey: "bathroom.electrical_changes",
      workAreaType: "bathroom",
      category: "scope",
    },
  ],
};
