import type { ScopeDefinition } from "@/lib/scopes/types";
import {
  BATHROOM_CEILING_LINING_FACT_KEY,
  BATHROOM_DEMOLITION_COMPONENT_OPTIONS,
  BATHROOM_DEMOLITION_COMPONENTS_FACT_KEY,
  BATHROOM_ELECTRICAL_LEVEL_FACT_KEY,
  BATHROOM_FIXTURE_CATALOGUE,
  BATHROOM_FIXTURE_OWNERSHIP_OPTIONS,
  BATHROOM_FC_FLOORING_SHEET_SIZE_OPTIONS,
  BATHROOM_FLOOR_FINISH_FACT_KEY,
  BATHROOM_FLOOR_FINISH_OPTIONS,
  BATHROOM_FLOOR_SUBSTRATE_FACT_KEY,
  BATHROOM_FLOOR_SUBSTRATE_OPTIONS,
  BATHROOM_FLOOR_SUBSTRATE_SHEET_SIZE_FACT_KEY,
  BATHROOM_FRAMING_LEVEL_FACT_KEY,
  BATHROOM_FRAMING_LEVEL_OPTIONS,
  BATHROOM_JOB_SCOPE_FACT_KEY,
  BATHROOM_JOB_SCOPE_OPTIONS,
  BATHROOM_PLUMBING_LEVEL_FACT_KEY,
  BATHROOM_SHOWER_DEPTH_FACT_KEY,
  BATHROOM_SHOWER_WALL_HEIGHT_FACT_KEY,
  BATHROOM_SHOWER_WIDTH_FACT_KEY,
  BATHROOM_TILE_FORMAT_FACT_KEY,
  BATHROOM_TILE_FORMAT_OPTIONS,
  BATHROOM_TRADE_LEVEL_OPTIONS,
  BATHROOM_WALL_TILE_EXTENT_OPTIONS,
  BATHROOM_WATERPROOFING_EXTENT_OPTIONS,
} from "@/lib/estimate/bathroom-scope";

export const bathroomScope: ScopeDefinition = {
  type: "bathroom",
  label: "Bathroom renovation",
  questions: [
    {
      key: BATHROOM_JOB_SCOPE_FACT_KEY,
      label: "Bathroom work",
      questionText: "What bathroom work are you doing?",
      inputType: "select",
      options: [...BATHROOM_JOB_SCOPE_OPTIONS],
      required: true,
      priority: 5,
      estimatePriorityClass: "P0",
      level1BlockingClass: "HARD_MINIMUM",
      factKey: BATHROOM_JOB_SCOPE_FACT_KEY,
      workAreaType: "bathroom",
      category: "scope",
    },
    {
      key: "bathroom.renovation_type",
      label: "Renovation type",
      questionText: "What type of bathroom renovation is this?",
      inputType: "select",
      options: [
        "Minor refresh",
        "Standard renovation",
        "Full strip-out and rebuild",
        "Not sure",
      ],
      required: false,
      priority: 6,
      estimatePriorityClass: "P3",
      factKey: "bathroom.renovation_type",
      workAreaType: "bathroom",
      category: "scope",
    },
    {
      key: "bathroom.demolition_required",
      label: "Demolition",
      questionText: "Is existing bathroom removal / strip-out included?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: true,
      priority: 15,
      estimatePriorityClass: "P0",
      level1BlockingClass: "ASSUMABLE",
      factKey: "bathroom.demolition_required",
      workAreaType: "bathroom",
      category: "scope",
    },
    {
      key: BATHROOM_DEMOLITION_COMPONENTS_FACT_KEY,
      label: "What is being stripped out",
      questionText: "What items are being removed?",
      inputType: "multi_select",
      options: [...BATHROOM_DEMOLITION_COMPONENT_OPTIONS],
      required: false,
      priority: 16,
      estimatePriorityClass: "P0",
      level1BlockingClass: "HARD_MINIMUM",
      factKey: BATHROOM_DEMOLITION_COMPONENTS_FACT_KEY,
      workAreaType: "bathroom",
      category: "scope",
    },
    {
      key: "bathroom.stopping_included",
      label: "Stopping / plastering",
      questionText: "Is stopping or plastering of new linings included?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 72,
      estimatePriorityClass: "P2",
      factKey: "bathroom.stopping_included",
      workAreaType: "bathroom",
      category: "finish",
    },
    {
      key: "bathroom.painting_included",
      label: "Painting",
      questionText: "Is painting of remaining bathroom surfaces included?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 73,
      estimatePriorityClass: "P2",
      factKey: "bathroom.painting_included",
      workAreaType: "bathroom",
      category: "finish",
    },
    {
      key: "bathroom.length_m",
      label: "Bathroom length",
      questionText: "What is the bathroom length?",
      inputType: "number",
      unit: "m",
      required: true,
      priority: 20,
      estimatePriorityClass: "P0",
      level1BlockingClass: "HARD_MINIMUM",
      factKey: "bathroom.length_m",
      workAreaType: "bathroom",
      category: "measurement",
    },
    {
      key: "bathroom.width_m",
      label: "Bathroom width",
      questionText: "What is the bathroom width?",
      inputType: "number",
      unit: "m",
      required: true,
      priority: 21,
      estimatePriorityClass: "P0",
      level1BlockingClass: "HARD_MINIMUM",
      factKey: "bathroom.width_m",
      workAreaType: "bathroom",
      category: "measurement",
    },
    {
      key: "bathroom.wall_height_m",
      label: "Wall height",
      questionText: "What is the bathroom wall height?",
      inputType: "number",
      unit: "m",
      required: false,
      priority: 22,
      estimatePriorityClass: "P0",
      level1BlockingClass: "ASSUMABLE",
      factKey: "bathroom.wall_height_m",
      workAreaType: "bathroom",
      category: "measurement",
    },
    {
      key: "bathroom.area_m2",
      label: "Bathroom area",
      questionText: "What is the approximate bathroom floor area?",
      inputType: "number",
      unit: "m²",
      required: false,
      priority: 23,
      estimatePriorityClass: "P3",
      factKey: "bathroom.area_m2",
      workAreaType: "bathroom",
      category: "measurement",
    },
    {
      key: BATHROOM_FLOOR_FINISH_FACT_KEY,
      label: "Floor finish",
      questionText: "What floor finish is being installed?",
      inputType: "select",
      options: [...BATHROOM_FLOOR_FINISH_OPTIONS],
      required: false,
      priority: 30,
      estimatePriorityClass: "P1",
      factKey: BATHROOM_FLOOR_FINISH_FACT_KEY,
      workAreaType: "bathroom",
      category: "finish",
    },
    {
      key: BATHROOM_TILE_FORMAT_FACT_KEY,
      label: "Tile format",
      questionText: "What tile format is being used?",
      inputType: "select",
      options: [...BATHROOM_TILE_FORMAT_OPTIONS],
      required: false,
      priority: 32,
      estimatePriorityClass: "P2",
      factKey: BATHROOM_TILE_FORMAT_FACT_KEY,
      workAreaType: "bathroom",
      category: "finish",
    },
    {
      key: "bathroom.tiling_included",
      label: "Tiling",
      questionText: "Is tiling included?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 35,
      estimatePriorityClass: "P1",
      factKey: "bathroom.tiling_included",
      workAreaType: "bathroom",
      category: "scope",
    },
    {
      key: "bathroom.tile_extent",
      label: "Wall tiling",
      questionText: "Are any bathroom walls being tiled, and to what extent?",
      inputType: "select",
      options: [...BATHROOM_WALL_TILE_EXTENT_OPTIONS],
      required: false,
      priority: 36,
      estimatePriorityClass: "P1",
      factKey: "bathroom.tile_extent",
      workAreaType: "bathroom",
      category: "scope",
    },
    {
      key: "bathroom.floor_tiling_area_m2",
      label: "Floor tiling area",
      questionText: "Approximate floor tiling area?",
      inputType: "number",
      unit: "m²",
      required: false,
      priority: 37,
      estimatePriorityClass: "P2",
      factKey: "bathroom.floor_tiling_area_m2",
      workAreaType: "bathroom",
      category: "measurement",
    },
    {
      key: "bathroom.wall_tiling_area_m2",
      label: "Wall tiling area",
      questionText: "Approximate wall tiling area?",
      inputType: "number",
      unit: "m²",
      required: false,
      priority: 38,
      estimatePriorityClass: "P2",
      factKey: "bathroom.wall_tiling_area_m2",
      workAreaType: "bathroom",
      category: "measurement",
    },
    {
      key: "bathroom.wall_tile_height",
      label: "Wall tile height",
      questionText: "What wall tiling height is required?",
      inputType: "select",
      options: [
        "Splashback only",
        "Half height",
        "Full height",
        "Wet area only",
        "Not sure",
      ],
      required: false,
      priority: 39,
      estimatePriorityClass: "P3",
      factKey: "bathroom.wall_tile_height",
      workAreaType: "bathroom",
      category: "scope",
    },
    {
      key: BATHROOM_SHOWER_WIDTH_FACT_KEY,
      label: "Shower width",
      questionText: "What is the shower width?",
      inputType: "number",
      unit: "m",
      required: false,
      priority: 39.1,
      estimatePriorityClass: "P1",
      factKey: BATHROOM_SHOWER_WIDTH_FACT_KEY,
      workAreaType: "bathroom",
      category: "measurement",
    },
    {
      key: BATHROOM_SHOWER_DEPTH_FACT_KEY,
      label: "Shower depth",
      questionText: "What is the shower depth?",
      inputType: "number",
      unit: "m",
      required: false,
      priority: 39.2,
      estimatePriorityClass: "P1",
      factKey: BATHROOM_SHOWER_DEPTH_FACT_KEY,
      workAreaType: "bathroom",
      category: "measurement",
    },
    {
      key: BATHROOM_SHOWER_WALL_HEIGHT_FACT_KEY,
      label: "Shower wall height",
      questionText: "What tiled / waterproofed shower wall height should be allowed for?",
      inputType: "number",
      unit: "m",
      required: false,
      priority: 39.3,
      estimatePriorityClass: "P1",
      factKey: BATHROOM_SHOWER_WALL_HEIGHT_FACT_KEY,
      workAreaType: "bathroom",
      category: "measurement",
    },
    {
      key: "bathroom.waterproofing_included",
      label: "Waterproofing",
      questionText: "Is waterproofing required?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: true,
      priority: 40,
      estimatePriorityClass: "P1",
      factKey: "bathroom.waterproofing_included",
      workAreaType: "bathroom",
      category: "scope",
    },
    {
      key: "bathroom.waterproofing_extent",
      label: "Waterproofing extent",
      questionText: "Where is waterproofing required?",
      inputType: "select",
      options: [...BATHROOM_WATERPROOFING_EXTENT_OPTIONS],
      required: false,
      priority: 41,
      estimatePriorityClass: "P1",
      factKey: "bathroom.waterproofing_extent",
      workAreaType: "bathroom",
      category: "scope",
    },
    {
      key: "bathroom.waterproofing_area_m2",
      label: "Waterproofing area",
      questionText: "What custom waterproofing area should be allowed for?",
      inputType: "number",
      unit: "m²",
      required: false,
      priority: 42,
      estimatePriorityClass: "P2",
      factKey: "bathroom.waterproofing_area_m2",
      workAreaType: "bathroom",
      category: "measurement",
    },
    {
      key: "bathroom.bath_surround_area_m2",
      label: "Bath surround area",
      questionText: "What bath-surround waterproofing area should be allowed for?",
      inputType: "number",
      unit: "m²",
      required: false,
      priority: 43,
      estimatePriorityClass: "P2",
      factKey: "bathroom.bath_surround_area_m2",
      workAreaType: "bathroom",
      category: "measurement",
    },
    {
      key: "bathroom.fixtures_client_supplied",
      label: "Client-supplied fixtures",
      questionText: "Is the client supplying the fixtures?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 45,
      estimatePriorityClass: "P2",
      factKey: "bathroom.fixtures_client_supplied",
      workAreaType: "bathroom",
      category: "scope",
    },
    {
      key: "bathroom.fixtures_included",
      label: "Fixtures included",
      questionText: "Which bathroom fixtures are in this job?",
      inputType: "multi_select",
      options: [...BATHROOM_FIXTURE_CATALOGUE],
      required: false,
      priority: 46,
      estimatePriorityClass: "P1",
      factKey: "bathroom.fixtures_included",
      workAreaType: "bathroom",
      category: "scope",
    },
    {
      key: "bathroom.shower_type",
      label: "Shower type",
      questionText: "What shower type is included?",
      inputType: "select",
      options: [
        "Acrylic",
        "Tiled shower",
        "Walk-in tiled shower",
        "Shower-over-bath",
        "Not sure",
      ],
      required: false,
      priority: 47,
      estimatePriorityClass: "P1",
      factKey: "bathroom.shower_type",
      workAreaType: "bathroom",
      category: "scope",
    },
    {
      key: BATHROOM_PLUMBING_LEVEL_FACT_KEY,
      label: "Plumbing intensity",
      questionText: "What level of plumbing work is included?",
      inputType: "select",
      options: [...BATHROOM_TRADE_LEVEL_OPTIONS],
      required: false,
      priority: 50,
      estimatePriorityClass: "P1",
      factKey: BATHROOM_PLUMBING_LEVEL_FACT_KEY,
      workAreaType: "bathroom",
      category: "scope",
    },
    {
      key: "bathroom.plumbing_changes",
      label: "Plumbing changes",
      questionText: "What level of plumbing changes are included?",
      inputType: "select",
      options: ["None", "Minor", "Major", "Not sure"],
      required: false,
      priority: 51,
      estimatePriorityClass: "P3",
      factKey: "bathroom.plumbing_changes",
      workAreaType: "bathroom",
      category: "scope",
    },
    {
      key: BATHROOM_ELECTRICAL_LEVEL_FACT_KEY,
      label: "Electrical intensity",
      questionText: "What level of electrical work is included?",
      inputType: "select",
      options: [...BATHROOM_TRADE_LEVEL_OPTIONS],
      required: false,
      priority: 55,
      estimatePriorityClass: "P1",
      factKey: BATHROOM_ELECTRICAL_LEVEL_FACT_KEY,
      workAreaType: "bathroom",
      category: "scope",
    },
    {
      key: "bathroom.electrical_changes",
      label: "Electrical changes",
      questionText: "What level of electrical changes are included?",
      inputType: "select",
      options: ["None", "Minor", "Major", "Not sure"],
      required: false,
      priority: 56,
      estimatePriorityClass: "P3",
      factKey: "bathroom.electrical_changes",
      workAreaType: "bathroom",
      category: "scope",
    },
    {
      key: "bathroom.plumbing.floor_waste_included",
      label: "Floor waste",
      questionText: "Is a new floor waste included?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 52,
      estimatePriorityClass: "P2",
      factKey: "bathroom.plumbing.floor_waste_included",
      workAreaType: "bathroom",
      category: "scope",
    },
    {
      key: "bathroom.plumbing.relocation_count",
      label: "Fixture relocations",
      questionText: "How many fixtures need a significant relocation?",
      inputType: "number",
      required: false,
      priority: 53,
      estimatePriorityClass: "P2",
      factKey: "bathroom.plumbing.relocation_count",
      workAreaType: "bathroom",
      category: "measurement",
    },
    {
      key: "bathroom.plumbing.scope_text",
      label: "Plumbing scope notes",
      questionText: "Any plumbing scope notes for the subcontractor?",
      inputType: "text",
      required: false,
      priority: 54,
      estimatePriorityClass: "P3",
      factKey: "bathroom.plumbing.scope_text",
      workAreaType: "bathroom",
      category: "scope",
    },
    {
      key: "bathroom.electrical.light_count",
      label: "Light points",
      questionText: "How many new bathroom light or downlight points?",
      inputType: "number",
      required: false,
      priority: 57,
      estimatePriorityClass: "P2",
      factKey: "bathroom.electrical.light_count",
      workAreaType: "bathroom",
      category: "measurement",
    },
    {
      key: "bathroom.electrical.gpo_count",
      label: "GPOs",
      questionText: "How many new GPOs are included?",
      inputType: "number",
      required: false,
      priority: 57,
      estimatePriorityClass: "P2",
      factKey: "bathroom.electrical.gpo_count",
      workAreaType: "bathroom",
      category: "measurement",
    },
    {
      key: "bathroom.electrical.mirror_power_included",
      label: "Mirror or vanity power",
      questionText: "Is mirror or vanity power included?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 57,
      estimatePriorityClass: "P2",
      factKey: "bathroom.electrical.mirror_power_included",
      workAreaType: "bathroom",
      category: "scope",
    },
    {
      key: "bathroom.electrical.new_circuit_included",
      label: "New circuit",
      questionText: "Is a new electrical circuit required?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 57,
      estimatePriorityClass: "P2",
      factKey: "bathroom.electrical.new_circuit_included",
      workAreaType: "bathroom",
      category: "scope",
    },
    {
      key: "bathroom.electrical.scope_text",
      label: "Electrical scope notes",
      questionText: "Any electrical scope notes for the subcontractor?",
      inputType: "text",
      required: false,
      priority: 57,
      estimatePriorityClass: "P3",
      factKey: "bathroom.electrical.scope_text",
      workAreaType: "bathroom",
      category: "scope",
    },
    {
      key: "bathroom.fixture.vanity.ownership",
      label: "Vanity supply / install",
      questionText: "Is the vanity supply, install, or both?",
      inputType: "select",
      options: [...BATHROOM_FIXTURE_OWNERSHIP_OPTIONS],
      required: false,
      priority: 48,
      estimatePriorityClass: "P2",
      factKey: "bathroom.fixture.vanity.ownership",
      workAreaType: "bathroom",
      category: "scope",
    },
    {
      key: "bathroom.fixture.toilet.ownership",
      label: "Toilet supply / install",
      questionText: "Is the toilet supply, install, or both?",
      inputType: "select",
      options: [...BATHROOM_FIXTURE_OWNERSHIP_OPTIONS],
      required: false,
      priority: 48,
      estimatePriorityClass: "P2",
      factKey: "bathroom.fixture.toilet.ownership",
      workAreaType: "bathroom",
      category: "scope",
    },
    {
      key: "bathroom.fixture.mirror.ownership",
      label: "Mirror supply / install",
      questionText: "Is the mirror supply, install, or both?",
      inputType: "select",
      options: [...BATHROOM_FIXTURE_OWNERSHIP_OPTIONS],
      required: false,
      priority: 48,
      estimatePriorityClass: "P2",
      factKey: "bathroom.fixture.mirror.ownership",
      workAreaType: "bathroom",
      category: "scope",
    },
    {
      key: "bathroom.fixture.shower.ownership",
      label: "Shower supply / install",
      questionText: "Is the shower tray/base supply, install, or both?",
      inputType: "select",
      options: [...BATHROOM_FIXTURE_OWNERSHIP_OPTIONS],
      required: false,
      priority: 48,
      estimatePriorityClass: "P2",
      factKey: "bathroom.fixture.shower.ownership",
      workAreaType: "bathroom",
      category: "scope",
    },
    {
      key: "bathroom.fixture.shower_enclosure.ownership",
      label: "Shower enclosure supply / install",
      questionText: "Is the shower enclosure supply, install, or both?",
      inputType: "select",
      options: [...BATHROOM_FIXTURE_OWNERSHIP_OPTIONS],
      required: false,
      priority: 48,
      estimatePriorityClass: "P2",
      factKey: "bathroom.fixture.shower_enclosure.ownership",
      workAreaType: "bathroom",
      category: "scope",
    },
    {
      key: "bathroom.ventilation_included",
      label: "Ventilation",
      questionText: "Is an extractor fan or ventilation included?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 56,
      estimatePriorityClass: "P1",
      factKey: "bathroom.ventilation_included",
      workAreaType: "bathroom",
      category: "scope",
    },
    {
      key: BATHROOM_FLOOR_SUBSTRATE_FACT_KEY,
      label: "Floor substrate",
      questionText: "What is the bathroom floor built on / being rebuilt with?",
      inputType: "select",
      options: [...BATHROOM_FLOOR_SUBSTRATE_OPTIONS],
      required: false,
      priority: 58,
      estimatePriorityClass: "P1",
      factKey: BATHROOM_FLOOR_SUBSTRATE_FACT_KEY,
      workAreaType: "bathroom",
      category: "scope",
    },
    {
      key: BATHROOM_FLOOR_SUBSTRATE_SHEET_SIZE_FACT_KEY,
      label: "Fibre-cement flooring size",
      questionText: "What 19 mm fibre-cement flooring sheet size is being used?",
      inputType: "select",
      options: [...BATHROOM_FC_FLOORING_SHEET_SIZE_OPTIONS],
      required: false,
      priority: 59,
      estimatePriorityClass: "P1",
      factKey: BATHROOM_FLOOR_SUBSTRATE_SHEET_SIZE_FACT_KEY,
      workAreaType: "bathroom",
      category: "scope",
    },
    {
      key: "bathroom.wall_lining_included",
      label: "Wall lining",
      questionText: "Are the bathroom walls being relined?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 60,
      estimatePriorityClass: "P1",
      factKey: "bathroom.wall_lining_included",
      workAreaType: "bathroom",
      category: "scope",
    },
    {
      key: BATHROOM_CEILING_LINING_FACT_KEY,
      label: "Ceiling lining",
      questionText: "Is the bathroom ceiling being relined?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 61,
      estimatePriorityClass: "P1",
      factKey: BATHROOM_CEILING_LINING_FACT_KEY,
      workAreaType: "bathroom",
      category: "scope",
    },
    {
      key: "bathroom.floor_prep_included",
      label: "Floor prep",
      questionText: "Is floor levelling/substrate prep included?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 61,
      estimatePriorityClass: "P1",
      factKey: "bathroom.floor_prep_included",
      workAreaType: "bathroom",
      category: "scope",
    },
    {
      key: BATHROOM_FRAMING_LEVEL_FACT_KEY,
      label: "Framing / nogging",
      questionText: "How much local framing or nogging is required?",
      inputType: "select",
      options: [...BATHROOM_FRAMING_LEVEL_OPTIONS],
      required: false,
      priority: 62,
      estimatePriorityClass: "P1",
      factKey: BATHROOM_FRAMING_LEVEL_FACT_KEY,
      workAreaType: "bathroom",
      category: "framing",
    },
    {
      key: "bathroom.underfloor_heating_included",
      label: "Underfloor heating",
      questionText: "Is underfloor heating included?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 63,
      estimatePriorityClass: "P2",
      factKey: "bathroom.underfloor_heating_included",
      workAreaType: "bathroom",
      category: "allowance",
    },
    {
      key: "bathroom.finish_level",
      label: "Finish level",
      questionText: "What finish level should be allowed for this bathroom?",
      inputType: "select",
      options: ["Budget", "Standard", "Premium", "Not sure"],
      required: false,
      priority: 80,
      estimatePriorityClass: "P1",
      factKey: "bathroom.finish_level",
      workAreaType: "bathroom",
      category: "finish",
    },
  ],
};
