import type { ScopeDefinition } from "@/lib/scopes/types";

export const bathroomScope: ScopeDefinition = {
  type: "bathroom",
  label: "Bathroom renovation",
  questions: [
    {
      key: "bathroom.area_m2",
      label: "Bathroom area",
      questionText: "What is the approximate bathroom floor area?",
      inputType: "number",
      unit: "m²",
      required: true,
      priority: 10,
      factKey: "bathroom.area_m2",
      workAreaType: "bathroom",
      category: "measurement",
    },
    {
      key: "bathroom.finish_level",
      label: "Finish level",
      questionText: "What finish level should be allowed for this bathroom?",
      inputType: "select",
      options: ["Budget", "Standard", "Premium", "Not sure"],
      required: true,
      priority: 20,
      factKey: "bathroom.finish_level",
      workAreaType: "bathroom",
      category: "finish",
    },
    {
      key: "bathroom.demolition_required",
      label: "Demolition",
      questionText: "Is demolition/strip-out included?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: true,
      priority: 30,
      factKey: "bathroom.demolition_required",
      workAreaType: "bathroom",
      category: "scope",
    },
    {
      key: "bathroom.fixtures_client_supplied",
      label: "Client-supplied fixtures",
      questionText: "Are bathroom fixtures client supplied?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: true,
      priority: 35,
      factKey: "bathroom.fixtures_client_supplied",
      workAreaType: "bathroom",
      category: "scope",
    },
    {
      key: "bathroom.fixtures_included",
      label: "Fixtures included",
      questionText: "Which fixtures are included in the contractor supply?",
      inputType: "multi_select",
      options: [
        "Toilet",
        "Shower",
        "Bath",
        "Vanity",
        "Basin",
        "Mixer/tapware",
        "Mirror/cabinet",
        "Towel rail",
        "Accessories",
        "Other",
      ],
      required: false,
      priority: 36,
      factKey: "bathroom.fixtures_included",
      workAreaType: "bathroom",
      category: "scope",
    },
    {
      key: "bathroom.waterproofing_included",
      label: "Waterproofing",
      questionText: "Is waterproofing included?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 40,
      factKey: "bathroom.waterproofing_included",
      workAreaType: "bathroom",
      category: "scope",
    },
    {
      key: "bathroom.tiling_included",
      label: "Tiling",
      questionText: "Is tiling included?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 45,
      factKey: "bathroom.tiling_included",
      workAreaType: "bathroom",
      category: "scope",
    },
    {
      key: "bathroom.floor_tiling_area_m2",
      label: "Floor tiling area",
      questionText: "Approximate floor tiling area?",
      inputType: "number",
      unit: "m²",
      required: false,
      priority: 46,
      factKey: "bathroom.floor_tiling_area_m2",
      workAreaType: "bathroom",
      category: "measurement",
    },
    {
      key: "bathroom.wall_tiling_area_m2",
      label: "Wall tiling area",
      questionText: "Approximate wall tiling area?",
      inputType: "number",
      unit: "m²",
      required: false,
      priority: 47,
      factKey: "bathroom.wall_tiling_area_m2",
      workAreaType: "bathroom",
      category: "measurement",
    },
    {
      key: "bathroom.tile_extent",
      label: "Tiling extent",
      questionText: "What tiling extent should be allowed for?",
      inputType: "select",
      options: [
        "Floor only",
        "Floor and walls",
        "Full height",
        "Splashback only",
        "Not sure",
      ],
      required: false,
      priority: 48,
      factKey: "bathroom.tile_extent",
      workAreaType: "bathroom",
      category: "scope",
    },
    {
      key: "bathroom.underfloor_heating_included",
      label: "Underfloor heating",
      questionText: "Is underfloor heating included?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 50,
      factKey: "bathroom.underfloor_heating_included",
      workAreaType: "bathroom",
      category: "allowance",
    },
    {
      key: "bathroom.plumbing_changes",
      label: "Plumbing changes",
      questionText: "What level of plumbing changes are included?",
      inputType: "select",
      options: ["None", "Minor", "Major", "Not sure"],
      required: false,
      priority: 55,
      factKey: "bathroom.plumbing_changes",
      workAreaType: "bathroom",
      category: "scope",
    },
    {
      key: "bathroom.electrical_changes",
      label: "Electrical changes",
      questionText: "What level of electrical changes are included?",
      inputType: "select",
      options: ["None", "Minor", "Major", "Not sure"],
      required: false,
      priority: 60,
      factKey: "bathroom.electrical_changes",
      workAreaType: "bathroom",
      category: "scope",
    },
  ],
};
