import type { ScopeDefinition } from "@/lib/scopes/types";

export const ceilingsScope: ScopeDefinition = {
  type: "ceilings",
  label: "Ceilings",
  questions: [
    {
      key: "ceilings.area_m2",
      label: "Ceiling area",
      questionText: "Approximate ceiling area?",
      inputType: "number",
      unit: "m²",
      required: true,
      priority: 10,
      factKey: "ceilings.area_m2",
      workAreaType: "ceilings",
      category: "measurement",
    },
    {
      key: "ceilings.structure_type",
      label: "Ceiling structure",
      questionText: "What ceiling structure is required?",
      inputType: "select",
      options: [
        "Rondo",
        "Timber batten",
        "Existing structure",
        "Suspended grid",
        "Other",
        "Not sure",
      ],
      required: true,
      priority: 20,
      factKey: "ceilings.structure_type",
      workAreaType: "ceilings",
      category: "scope",
    },
    {
      key: "ceilings.ceiling_type",
      label: "Ceiling lining",
      questionText: "What type of ceiling is required?",
      inputType: "select",
      options: [
        "Plasterboard",
        "Ceiling tiles",
        "Plywood",
        "Fibre cement",
        "Other",
        "Not sure",
      ],
      required: true,
      priority: 30,
      factKey: "ceilings.ceiling_type",
      workAreaType: "ceilings",
      category: "scope",
    },
    {
      key: "ceilings.plasterboard_type",
      label: "Plasterboard type",
      questionText: "What plasterboard ceiling board type is required?",
      inputType: "select",
      options: [
        "Standard",
        "Fyreline",
        "Aqualine",
        "Braceline",
        "Other",
        "Not sure",
      ],
      required: false,
      priority: 35,
      factKey: "ceilings.plasterboard_type",
      workAreaType: "ceilings",
      category: "scope",
    },
    {
      key: "ceilings.edge_lining_type",
      label: "Edge linings",
      questionText: "Are edge linings included?",
      inputType: "select",
      options: ["None", "Scotia", "Cove", "Square stop", "Other", "Not sure"],
      required: false,
      priority: 40,
      factKey: "ceilings.edge_lining_type",
      workAreaType: "ceilings",
      category: "scope",
    },
    {
      key: "ceilings.edge_lining_length_lm",
      label: "Edge lining length",
      questionText: "Approximate edge lining length?",
      inputType: "number",
      unit: "lm",
      required: false,
      priority: 41,
      factKey: "ceilings.edge_lining_length_lm",
      workAreaType: "ceilings",
      category: "measurement",
    },
    {
      key: "ceilings.demolition_included",
      label: "Demolition",
      questionText: "Is demolition/removal of existing ceiling included?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 12,
      factKey: "ceilings.demolition_included",
      workAreaType: "ceilings",
      category: "scope",
    },
    {
      key: "ceilings.battens_included",
      label: "Battens/framing",
      questionText: "Are ceiling battens/framing included?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 25,
      factKey: "ceilings.battens_included",
      workAreaType: "ceilings",
      category: "scope",
    },
    {
      key: "ceilings.stopping_included",
      label: "Stopping/plastering",
      questionText: "Is stopping/plastering included?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 45,
      factKey: "ceilings.stopping_included",
      workAreaType: "ceilings",
      category: "scope",
    },
    {
      key: "ceilings.painting_included",
      label: "Painting",
      questionText: "Is ceiling painting included?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 46,
      factKey: "ceilings.painting_included",
      workAreaType: "ceilings",
      category: "scope",
    },
    {
      key: "ceilings.access",
      label: "Ceiling working height",
      questionText: "What is the working height for this ceiling?",
      inputType: "select",
      options: ["Standard", "High", "Difficult working height", "Not sure"],
      required: false,
      priority: 55,
      factKey: "ceilings.access",
      workAreaType: "ceilings",
      category: "scope",
    },
    {
      key: "ceilings.insulation_included",
      label: "Insulation",
      questionText: "Is ceiling insulation included?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 50,
      factKey: "ceilings.insulation_included",
      workAreaType: "ceilings",
      category: "scope",
    },
    {
      key: "ceilings.portion.job_scope",
      label: "Ceiling work",
      questionText: "What ceiling work is required in this portion?",
      inputType: "select",
      options: [
        "new_ceiling",
        "replacement_lining_only",
        "complete_replacement",
        "reline_existing_suitable_framing",
      ],
      required: false,
      priority: 11,
      factKey: "ceilings.portion.job_scope",
      workAreaType: "ceilings",
      category: "scope",
    },
    {
      key: "ceilings.portion.structure_family",
      label: "Ceiling structure",
      questionText: "What ceiling structure is required in this portion?",
      inputType: "select",
      options: [
        "existing_framing",
        "timber_direct_fix",
        "steel_direct_fix",
        "suspended_steel",
        "tile_and_grid",
      ],
      required: false,
      priority: 21,
      factKey: "ceilings.portion.structure_family",
      workAreaType: "ceilings",
      category: "scope",
    },
    {
      key: "ceilings.portion.lining_family",
      label: "Ceiling lining",
      questionText: "What lining is required in this portion?",
      inputType: "select",
      options: ["plasterboard", "plywood", "timber_lined", "tile_and_grid"],
      required: false,
      priority: 31,
      factKey: "ceilings.portion.lining_family",
      workAreaType: "ceilings",
      category: "scope",
    },
    {
      key: "ceilings.portion.length_m",
      label: "Ceiling length",
      questionText: "What is the length of this ceiling portion?",
      inputType: "number",
      unit: "m",
      required: false,
      priority: 13,
      factKey: "ceilings.portion.length_m",
      workAreaType: "ceilings",
      category: "measurement",
    },
    {
      key: "ceilings.portion.width_m",
      label: "Ceiling width",
      questionText: "What is the width of this ceiling portion?",
      inputType: "number",
      unit: "m",
      required: false,
      priority: 14,
      factKey: "ceilings.portion.width_m",
      workAreaType: "ceilings",
      category: "measurement",
    },
    {
      key: "ceilings.portion.area_m2",
      label: "Ceiling area",
      questionText: "What is the area of this ceiling portion?",
      inputType: "number",
      unit: "m²",
      required: false,
      priority: 15,
      factKey: "ceilings.portion.area_m2",
      workAreaType: "ceilings",
      category: "measurement",
    },
    {
      key: "ceilings.portion.drop_height_m",
      label: "Drop height",
      questionText: "What is the suspended ceiling drop height?",
      inputType: "number",
      unit: "m",
      required: false,
      priority: 26,
      factKey: "ceilings.portion.drop_height_m",
      workAreaType: "ceilings",
      category: "measurement",
    },
    {
      key: "ceilings.portion.bulkheads_present",
      label: "Bulkheads",
      questionText: "Does this ceiling portion include bulkheads?",
      inputType: "boolean",
      options: ["Yes", "No"],
      required: false,
      priority: 52,
      factKey: "ceilings.portion.bulkheads_present",
      workAreaType: "ceilings",
      category: "scope",
    },
  ],
};
