import type { ScopeDefinition } from "@/lib/scopes/types";

export const deckScope: ScopeDefinition = {
  type: "deck",
  label: "Deck",
  questions: [
    {
      key: "deck.length_m",
      label: "Length of deck",
      questionText: "What is the deck length?",
      inputType: "number",
      unit: "m",
      required: true,
      priority: 10,
      estimatePriorityClass: "P0",
      level1BlockingClass: "HARD_MINIMUM",
      factKey: "deck.length_m",
      workAreaType: "deck",
      category: "measurement",
    },
    {
      key: "deck.width_m",
      label: "Width of deck",
      questionText: "What is the deck width?",
      inputType: "number",
      unit: "m",
      required: true,
      priority: 20,
      estimatePriorityClass: "P0",
      level1BlockingClass: "HARD_MINIMUM",
      factKey: "deck.width_m",
      workAreaType: "deck",
      category: "measurement",
    },
    {
      key: "deck.area_m2",
      label: "Deck area",
      questionText: "What is the approximate deck area?",
      inputType: "number",
      unit: "m²",
      required: true,
      priority: 25,
      estimatePriorityClass: "P3",
      factKey: "deck.area_m2",
      workAreaType: "deck",
      category: "measurement",
    },
    {
      key: "deck.height_m",
      label: "Deck height",
      questionText: "Approximate deck height above ground?",
      inputType: "number",
      unit: "m",
      required: true,
      priority: 28,
      estimatePriorityClass: "P0",
      level1BlockingClass: "ASSUMABLE",
      factKey: "deck.height_m",
      workAreaType: "deck",
      category: "measurement",
    },
    {
      key: "deck.level",
      label: "Deck level",
      questionText: "Is the deck ground-level or elevated?",
      inputType: "select",
      options: ["Ground-level", "Elevated", "Not sure"],
      required: false,
      priority: 29,
      estimatePriorityClass: "P1",
      factKey: "deck.level",
      workAreaType: "deck",
      category: "scope",
    },
    {
      key: "deck.board_material",
      label: "Decking board material",
      questionText: "What decking is being used?",
      inputType: "select",
      options: [
        "Treated Pine",
        "Hardwood",
        "Kwila",
        "Composite",
        "Other",
        "Not sure",
      ],
      required: true,
      priority: 30,
      estimatePriorityClass: "P0",
      level1BlockingClass: "ASSUMABLE",
      factKey: "deck.board_material",
      workAreaType: "deck",
      category: "scope",
    },
    {
      key: "deck.board_width_mm",
      label: "Decking board width",
      questionText: "What decking board width is being used?",
      inputType: "select",
      options: ["90", "140", "150", "Other", "Not sure"],
      unit: "mm",
      required: false,
      priority: 35,
      estimatePriorityClass: "P1",
      factKey: "deck.board_width_mm",
      workAreaType: "deck",
      category: "scope",
    },
    {
      key: "deck.existing_deck_removal",
      label: "Existing deck removal",
      questionText: "Does the existing deck need removing?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 45,
      estimatePriorityClass: "P0",
      level1BlockingClass: "ASSUMABLE",
      factKey: "deck.existing_deck_removal",
      workAreaType: "deck",
      category: "scope",
    },
    {
      key: "deck.access_type",
      label: "Deck access",
      questionText:
        "Is access from the deck by steps, a stair set, or no stairs?",
      inputType: "select",
      options: [
        "None",
        "Single step or step-down",
        "Stair set",
        "Multiple sides step-down",
        "Not sure",
      ],
      required: false,
      priority: 50,
      estimatePriorityClass: "P1",
      factKey: "deck.access_type",
      workAreaType: "deck",
      category: "scope",
    },
    {
      key: "deck.steps_included",
      label: "Steps",
      questionText: "Are new steps included in this deck job?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 51,
      estimatePriorityClass: "P1",
      factKey: "deck.steps_included",
      workAreaType: "deck",
      category: "scope",
    },
    {
      key: "deck.step_width_m",
      label: "Stair width",
      questionText: "How wide are the stairs?",
      inputType: "number",
      unit: "m",
      required: false,
      priority: 51.4,
      estimatePriorityClass: "P2",
      factKey: "deck.step_width_m",
      workAreaType: "deck",
      category: "measurement",
    },
    {
      key: "deck.step_going_m",
      label: "Tread depth",
      questionText: "How deep are the stair treads?",
      inputType: "number",
      unit: "m",
      required: false,
      priority: 51.5,
      estimatePriorityClass: "P2",
      factKey: "deck.step_going_m",
      workAreaType: "deck",
      category: "measurement",
    },
    {
      key: "deck.vertical_face_boards_required",
      label: "Fascia / edge boards",
      questionText: "Are fascia / edge boards included?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 55,
      estimatePriorityClass: "P1",
      factKey: "deck.vertical_face_boards_required",
      workAreaType: "deck",
      category: "scope",
    },
    {
      key: "deck.skirting_included",
      label: "Full-height deck skirting / screening",
      questionText: "Is full-height deck skirting / screening included?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 55.5,
      estimatePriorityClass: "P2",
      factKey: "deck.skirting_included",
      workAreaType: "deck",
      category: "scope",
    },
    {
      key: "deck.vertical_face_board_length_lm",
      label: "Fascia / edge-board length",
      questionText: "Approximate fascia / edge-board length?",
      inputType: "number",
      unit: "lm",
      required: false,
      priority: 56,
      estimatePriorityClass: "P1",
      factKey: "deck.vertical_face_board_length_lm",
      workAreaType: "deck",
      category: "measurement",
    },
    {
      key: "deck.balustrade_required",
      label: "Balustrade",
      questionText: "Is a balustrade required?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 60,
      estimatePriorityClass: "P1",
      factKey: "deck.balustrade_required",
      workAreaType: "deck",
      category: "scope",
    },
    {
      key: "deck.handrail_required",
      label: "Handrail",
      questionText: "Is a handrail required (without full balustrade)?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 61,
      estimatePriorityClass: "P1",
      factKey: "deck.handrail_required",
      workAreaType: "deck",
      category: "scope",
    },
    {
      key: "deck.substructure_included",
      label: "Substructure/framing",
      questionText: "Is new framing included?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 65,
      estimatePriorityClass: "P1",
      factKey: "deck.substructure_included",
      workAreaType: "deck",
      category: "scope",
    },
    {
      key: "deck.concrete_to_supports",
      label: "Concrete to supports",
      questionText: "Is concrete included at piles or posts?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 65.5,
      estimatePriorityClass: "P1",
      factKey: "deck.concrete_to_supports",
      workAreaType: "deck",
      category: "scope",
    },
    {
      key: "deck.pile_or_post_replacement_required",
      label: "Pile/post replacement",
      questionText:
        "Are any piles, posts or substructure members being replaced?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 66,
      estimatePriorityClass: "P1",
      factKey: "deck.pile_or_post_replacement_required",
      workAreaType: "deck",
      category: "scope",
    },
    {
      key: "deck.pile_or_post_count",
      label: "Piles/posts to replace",
      questionText: "Approximate number of piles or posts to replace?",
      inputType: "number",
      required: false,
      priority: 67,
      estimatePriorityClass: "P1",
      factKey: "deck.pile_or_post_count",
      workAreaType: "deck",
      category: "measurement",
    },
    {
      key: "deck.substructure_condition",
      label: "Substructure condition",
      questionText: "What is the existing substructure condition?",
      inputType: "select",
      options: [
        "good_existing",
        "partial_replacement",
        "full_replacement",
        "none",
        "unknown",
      ],
      required: false,
      priority: 68,
      estimatePriorityClass: "P1",
      factKey: "deck.substructure_condition",
      workAreaType: "deck",
      category: "scope",
    },
    {
      key: "deck.engineering_or_consent_status",
      label: "Engineering/consent",
      questionText: "Does this deck need consent or engineering?",
      inputType: "select",
      options: ["Not required", "Required", "Not sure"],
      required: false,
      priority: 70,
      estimatePriorityClass: "P2",
      factKey: "deck.engineering_or_consent_status",
      workAreaType: "deck",
      category: "risk",
    },
    {
      key: "deck.board_direction",
      label: "Board direction",
      questionText: "Which way do the decking boards run?",
      inputType: "select",
      options: ["Along length", "Along width"],
      required: false,
      priority: 71,
      estimatePriorityClass: "P2",
      factKey: "deck.board_direction",
      workAreaType: "deck",
      category: "framing",
    },
    {
      key: "deck.joist_direction",
      label: "Joist direction",
      questionText: "Which way do the joists run?",
      inputType: "select",
      options: ["Along length", "Along width"],
      required: false,
      priority: 72,
      estimatePriorityClass: "P2",
      factKey: "deck.joist_direction",
      workAreaType: "deck",
      category: "framing",
    },
    {
      key: "deck.joist_section",
      label: "Joist size",
      questionText: "What joist size is being used?",
      inputType: "text",
      required: false,
      priority: 73,
      estimatePriorityClass: "P2",
      factKey: "deck.joist_section",
      workAreaType: "deck",
      category: "framing",
    },
    {
      key: "deck.joist_centres_mm",
      label: "Joist spacing",
      questionText: "Joist centres (mm)?",
      inputType: "number",
      unit: "mm",
      required: false,
      priority: 74,
      estimatePriorityClass: "P2",
      factKey: "deck.joist_centres_mm",
      workAreaType: "deck",
      category: "framing",
    },
    {
      key: "deck.framing_treatment",
      label: "Framing treatment",
      questionText: "Framing treatment or specification?",
      inputType: "text",
      required: false,
      priority: 75,
      estimatePriorityClass: "P2",
      factKey: "deck.framing_treatment",
      workAreaType: "deck",
      category: "framing",
    },
    {
      key: "deck.bearer_section",
      label: "Bearer size",
      questionText: "What bearer size is being used?",
      inputType: "text",
      required: false,
      priority: 76,
      estimatePriorityClass: "P2",
      factKey: "deck.bearer_section",
      workAreaType: "deck",
      category: "framing",
    },
    {
      key: "deck.bearer_row_count",
      label: "Bearer rows",
      questionText: "How many bearer rows?",
      inputType: "number",
      required: false,
      priority: 77,
      estimatePriorityClass: "P2",
      factKey: "deck.bearer_row_count",
      workAreaType: "deck",
      category: "framing",
    },
    {
      key: "deck.support_type",
      label: "Support type",
      questionText: "Post, pile, or other support type?",
      inputType: "text",
      required: false,
      priority: 78,
      estimatePriorityClass: "P2",
      factKey: "deck.support_type",
      workAreaType: "deck",
      category: "supports",
    },
    {
      key: "deck.supports_per_bearer",
      label: "Supports per bearer",
      questionText: "How many supports along each bearer?",
      inputType: "number",
      required: false,
      priority: 79,
      estimatePriorityClass: "P2",
      factKey: "deck.supports_per_bearer",
      workAreaType: "deck",
      category: "supports",
    },
    {
      key: "deck.support_section",
      label: "Support size",
      questionText: "Post/pile size or specification?",
      inputType: "text",
      required: false,
      priority: 80,
      estimatePriorityClass: "P2",
      factKey: "deck.support_section",
      workAreaType: "deck",
      category: "supports",
    },
    {
      key: "deck.footing_length_mm",
      label: "Footing length",
      questionText: "Footing length (mm), if known?",
      inputType: "number",
      unit: "mm",
      required: false,
      priority: 81,
      estimatePriorityClass: "P2",
      factKey: "deck.footing_length_mm",
      workAreaType: "deck",
      category: "footings",
    },
    {
      key: "deck.footing_width_mm",
      label: "Footing width",
      questionText: "Footing width (mm), if known?",
      inputType: "number",
      unit: "mm",
      required: false,
      priority: 82,
      estimatePriorityClass: "P2",
      factKey: "deck.footing_width_mm",
      workAreaType: "deck",
      category: "footings",
    },
    {
      key: "deck.footing_depth_mm",
      label: "Footing depth",
      questionText: "Footing depth (mm), if known?",
      inputType: "number",
      unit: "mm",
      required: false,
      priority: 83,
      estimatePriorityClass: "P2",
      factKey: "deck.footing_depth_mm",
      workAreaType: "deck",
      category: "footings",
    },
    {
      key: "deck.pergola_included",
      label: "Pergola",
      questionText: "Is the pergola included in this estimate?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 75,
      estimatePriorityClass: "P1",
      factKey: "deck.pergola_included",
      workAreaType: "deck",
      category: "allowance",
    },
  ],
};
