import type { ScopeDefinition } from "@/lib/scopes/types";

export const deckScope: ScopeDefinition = {
  type: "deck",
  label: "Deck",
  questions: [
    {
      key: "deck.length_m",
      label: "Length of deck",
      questionText: "What is the deck length?",
      inputType: "number",
      unit: "m",
      required: true,
      priority: 10,
      factKey: "deck.length_m",
      workAreaType: "deck",
      category: "measurement",
    },
    {
      key: "deck.width_m",
      label: "Width of deck",
      questionText: "What is the deck width?",
      inputType: "number",
      unit: "m",
      required: true,
      priority: 20,
      factKey: "deck.width_m",
      workAreaType: "deck",
      category: "measurement",
    },
    {
      key: "deck.area_m2",
      label: "Deck area",
      questionText: "What is the approximate deck area?",
      inputType: "number",
      unit: "m²",
      required: true,
      priority: 25,
      factKey: "deck.area_m2",
      workAreaType: "deck",
      category: "measurement",
    },
    {
      key: "deck.height_m",
      label: "Deck height",
      questionText: "Approximate deck height above ground?",
      inputType: "number",
      unit: "m",
      required: true,
      priority: 28,
      factKey: "deck.height_m",
      workAreaType: "deck",
      category: "measurement",
    },
    {
      key: "deck.board_material",
      label: "Decking board material",
      questionText: "What decking board material/type is being allowed for?",
      inputType: "select",
      options: [
        "Treated Pine",
        "Hardwood",
        "Kwila",
        "Composite",
        "Other",
        "Not sure",
      ],
      required: true,
      priority: 30,
      factKey: "deck.board_material",
      workAreaType: "deck",
      category: "scope",
    },
    {
      key: "deck.board_width_mm",
      label: "Decking board width",
      questionText: "What decking board width is being used?",
      inputType: "select",
      options: ["90", "140", "150", "Other", "Not sure"],
      unit: "mm",
      required: false,
      priority: 35,
      factKey: "deck.board_width_mm",
      workAreaType: "deck",
      category: "scope",
    },
    {
      key: "deck.board_wastage_percent",
      label: "Board wastage allowance",
      questionText: "Wastage allowance for decking boards?",
      inputType: "number",
      unit: "%",
      required: false,
      priority: 36,
      factKey: "deck.board_wastage_percent",
      workAreaType: "deck",
      category: "allowance",
    },
    {
      key: "deck.existing_deck_removal",
      label: "Existing deck removal",
      questionText: "Is removal of an existing deck required?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 45,
      factKey: "deck.existing_deck_removal",
      workAreaType: "deck",
      category: "scope",
    },
    {
      key: "deck.access_type",
      label: "Deck access",
      questionText:
        "Is access from the deck by steps, a stair set, or no stairs?",
      inputType: "select",
      options: [
        "None",
        "Single step or step-down",
        "Stair set",
        "Multiple sides step-down",
        "Not sure",
      ],
      required: false,
      priority: 50,
      factKey: "deck.access_type",
      workAreaType: "deck",
      category: "scope",
    },
    {
      key: "deck.vertical_face_boards_required",
      label: "Vertical face boards",
      questionText:
        "Are vertical boards/fascia required down the side of the deck?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 55,
      factKey: "deck.vertical_face_boards_required",
      workAreaType: "deck",
      category: "scope",
    },
    {
      key: "deck.vertical_face_board_length_lm",
      label: "Face board length",
      questionText: "Approximate total length of vertical face boards?",
      inputType: "number",
      unit: "lm",
      required: false,
      priority: 56,
      factKey: "deck.vertical_face_board_length_lm",
      workAreaType: "deck",
      category: "measurement",
    },
    {
      key: "deck.balustrade_required",
      label: "Balustrade",
      questionText: "Is a balustrade required?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 60,
      factKey: "deck.balustrade_required",
      workAreaType: "deck",
      category: "scope",
    },
    {
      key: "deck.pergola_included",
      label: "Pergola",
      questionText: "Is the pergola included in this estimate?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 70,
      factKey: "deck.pergola_included",
      workAreaType: "deck",
      category: "allowance",
    },
  ],
};
