import type { ScopeDefinition } from "@/lib/scopes/types";

export const deckScope: ScopeDefinition = {
  type: "deck",
  label: "Deck",
  questions: [
    {
      key: "deck.length_m",
      label: "Length of deck",
      questionText: "What is the deck length?",
      inputType: "number",
      unit: "m",
      required: true,
      priority: 10,
      factKey: "deck.length_m",
      workAreaType: "deck",
      category: "measurement",
    },
    {
      key: "deck.width_m",
      label: "Width of deck",
      questionText: "What is the deck width?",
      inputType: "number",
      unit: "m",
      required: true,
      priority: 20,
      factKey: "deck.width_m",
      workAreaType: "deck",
      category: "measurement",
    },
    {
      key: "deck.area_m2",
      label: "Deck area",
      questionText: "What is the approximate deck area?",
      inputType: "number",
      unit: "m²",
      required: true,
      priority: 25,
      factKey: "deck.area_m2",
      workAreaType: "deck",
      category: "measurement",
    },
    {
      key: "deck.height_m",
      label: "Deck height",
      questionText: "Approximate deck height above ground?",
      inputType: "number",
      unit: "m",
      required: true,
      priority: 28,
      factKey: "deck.height_m",
      workAreaType: "deck",
      category: "measurement",
    },
    {
      key: "deck.level",
      label: "Deck level",
      questionText: "Is the deck ground-level or elevated?",
      inputType: "select",
      options: ["Ground-level", "Elevated", "Not sure"],
      required: false,
      priority: 29,
      factKey: "deck.level",
      workAreaType: "deck",
      category: "scope",
    },
    {
      key: "deck.board_material",
      label: "Decking board material",
      questionText: "What decking board material/type is being allowed for?",
      inputType: "select",
      options: [
        "Treated Pine",
        "Hardwood",
        "Kwila",
        "Composite",
        "Other",
        "Not sure",
      ],
      required: true,
      priority: 30,
      factKey: "deck.board_material",
      workAreaType: "deck",
      category: "scope",
    },
    {
      key: "deck.board_width_mm",
      label: "Decking board width",
      questionText: "What decking board width is being used?",
      inputType: "select",
      options: ["90", "140", "150", "Other", "Not sure"],
      unit: "mm",
      required: false,
      priority: 35,
      factKey: "deck.board_width_mm",
      workAreaType: "deck",
      category: "scope",
    },
    {
      key: "deck.existing_deck_removal",
      label: "Existing deck removal",
      questionText: "Is removal of an existing deck required?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 45,
      factKey: "deck.existing_deck_removal",
      workAreaType: "deck",
      category: "scope",
    },
    {
      key: "deck.access",
      label: "Access difficulty",
      questionText: "How difficult is site access for this deck?",
      inputType: "select",
      options: ["Easy", "Moderate", "Difficult", "Not sure"],
      required: false,
      priority: 48,
      factKey: "deck.access",
      workAreaType: "deck",
      category: "risk",
    },
    {
      key: "deck.access_type",
      label: "Deck access",
      questionText:
        "Is access from the deck by steps, a stair set, or no stairs?",
      inputType: "select",
      options: [
        "None",
        "Single step or step-down",
        "Stair set",
        "Multiple sides step-down",
        "Not sure",
      ],
      required: false,
      priority: 50,
      factKey: "deck.access_type",
      workAreaType: "deck",
      category: "scope",
    },
    {
      key: "deck.vertical_face_boards_required",
      label: "Vertical face boards",
      questionText:
        "Are vertical boards/fascia required down the side of the deck?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 55,
      factKey: "deck.vertical_face_boards_required",
      workAreaType: "deck",
      category: "scope",
    },
    {
      key: "deck.vertical_face_board_length_lm",
      label: "Face board length",
      questionText: "Approximate total length of vertical face boards?",
      inputType: "number",
      unit: "lm",
      required: false,
      priority: 56,
      factKey: "deck.vertical_face_board_length_lm",
      workAreaType: "deck",
      category: "measurement",
    },
    {
      key: "deck.balustrade_required",
      label: "Balustrade",
      questionText: "Is a balustrade required?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 60,
      factKey: "deck.balustrade_required",
      workAreaType: "deck",
      category: "scope",
    },
    {
      key: "deck.handrail_required",
      label: "Handrail",
      questionText: "Is a handrail required (without full balustrade)?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 61,
      factKey: "deck.handrail_required",
      workAreaType: "deck",
      category: "scope",
    },
    {
      key: "deck.substructure_included",
      label: "Substructure/framing",
      questionText: "Is framing/substructure included in this scope?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 65,
      factKey: "deck.substructure_included",
      workAreaType: "deck",
      category: "scope",
    },
    {
      key: "deck.pile_or_post_replacement_required",
      label: "Pile/post replacement",
      questionText:
        "Are any piles, posts or substructure members being replaced?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 66,
      factKey: "deck.pile_or_post_replacement_required",
      workAreaType: "deck",
      category: "scope",
    },
    {
      key: "deck.pile_or_post_count",
      label: "Piles/posts to replace",
      questionText: "Approximate number of piles or posts to replace?",
      inputType: "number",
      required: false,
      priority: 67,
      factKey: "deck.pile_or_post_count",
      workAreaType: "deck",
      category: "measurement",
    },
    {
      key: "deck.substructure_condition",
      label: "Substructure condition",
      questionText: "What is the existing substructure condition?",
      inputType: "select",
      options: [
        "good_existing",
        "partial_replacement",
        "full_replacement",
        "unknown",
      ],
      required: false,
      priority: 68,
      factKey: "deck.substructure_condition",
      workAreaType: "deck",
      category: "scope",
    },
    {
      key: "deck.engineering_or_consent_status",
      label: "Engineering/consent",
      questionText: "Is engineering or building consent required?",
      inputType: "select",
      options: ["Not required", "Required", "Not sure"],
      required: false,
      priority: 70,
      factKey: "deck.engineering_or_consent_status",
      workAreaType: "deck",
      category: "risk",
    },
    {
      key: "deck.pergola_included",
      label: "Pergola",
      questionText: "Is the pergola included in this estimate?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 75,
      factKey: "deck.pergola_included",
      workAreaType: "deck",
      category: "allowance",
    },
  ],
};
