import type { ScopeDefinition } from "@/lib/scopes/types";

/** Standalone demolition/strip-out scope — only used when demolition is a confirmed work area. */
export const demolitionScope: ScopeDefinition = {
  type: "demolition",
  label: "Demolition / strip-out",
  questions: [
    {
      key: "demolition.scope_items",
      label: "Demolition scope",
      questionText: "What demolition/strip-out items are included?",
      inputType: "multi_select",
      options: [
        "Internal walls",
        "Flooring",
        "Ceilings",
        "Doors",
        "Kitchen",
        "Bathroom",
        "Fixtures",
        "Linings",
        "General strip-out",
        "Exterior structure",
        "Other",
      ],
      required: true,
      priority: 5,
      factKey: "demolition.scope_items",
      workAreaType: "demolition",
      category: "scope",
    },
    {
      key: "demolition.area_m2",
      label: "Demolition area",
      questionText: "What approximate area is being demolished or stripped out?",
      inputType: "number",
      unit: "m²",
      required: false,
      priority: 10,
      factKey: "demolition.area_m2",
      workAreaType: "demolition",
      category: "measurement",
    },
    {
      key: "demolition.disposal_included",
      label: "Disposal",
      questionText: "Is waste removal/disposal included?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: true,
      priority: 20,
      factKey: "demolition.disposal_included",
      workAreaType: "demolition",
      category: "scope",
    },
    {
      key: "demolition.hazardous_materials_suspected",
      label: "Hazardous materials",
      questionText: "Are hazardous materials suspected?",
      inputType: "select",
      options: [
        "No",
        "Asbestos possible",
        "Lead paint possible",
        "Not sure",
      ],
      required: false,
      priority: 30,
      factKey: "demolition.hazardous_materials_suspected",
      workAreaType: "demolition",
      category: "risk",
    },
    {
      key: "demolition.services_isolation_required",
      label: "Services isolation",
      questionText: "Is services isolation required before demolition?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 40,
      factKey: "demolition.services_isolation_required",
      workAreaType: "demolition",
      category: "risk",
    },
    {
      key: "demolition.access",
      label: "Access",
      questionText: "How difficult is access for removal?",
      inputType: "select",
      options: ["Easy", "Moderate", "Difficult", "Not sure"],
      required: false,
      priority: 50,
      factKey: "demolition.access",
      workAreaType: "demolition",
      category: "risk",
    },
  ],
};
