import type { ScopeDefinition } from "@/lib/scopes/types";

/** Standalone demolition/strip-out scope — only used when demolition is a confirmed work area. */
export const demolitionScope: ScopeDefinition = {
  type: "demolition",
  label: "Demolition / strip-out",
  questions: [
    {
      key: "demolition.scope_items",
      label: "Demolition scope",
      questionText: "What demolition/strip-out items are included?",
      inputType: "multi_select",
      options: [
        "Internal walls",
        "Flooring",
        "Ceilings",
        "Doors",
        "Kitchen",
        "Bathroom",
        "Fixtures",
        "Joinery",
        "General strip-out",
        "Exterior",
        "Other",
      ],
      required: true,
      priority: 5,
      factKey: "demolition.scope_items",
      workAreaType: "demolition",
      category: "scope",
    },
    {
      key: "demolition.area_m2",
      label: "General demolition area",
      questionText: "What approximate total area is being demolished or stripped out?",
      inputType: "number",
      unit: "m²",
      required: false,
      priority: 10,
      factKey: "demolition.area_m2",
      workAreaType: "demolition",
      category: "measurement",
    },
    {
      key: "demolition.wall_length_m",
      label: "Wall removal length",
      questionText: "Approximate length of walls to remove?",
      inputType: "number",
      unit: "lm",
      required: false,
      priority: 11,
      factKey: "demolition.wall_length_m",
      workAreaType: "demolition",
      category: "measurement",
    },
    {
      key: "demolition.floor_area_m2",
      label: "Floor removal area",
      questionText: "Approximate floor area to remove?",
      inputType: "number",
      unit: "m²",
      required: false,
      priority: 12,
      factKey: "demolition.floor_area_m2",
      workAreaType: "demolition",
      category: "measurement",
    },
    {
      key: "demolition.ceiling_area_m2",
      label: "Ceiling removal area",
      questionText: "Approximate ceiling area to remove?",
      inputType: "number",
      unit: "m²",
      required: false,
      priority: 13,
      factKey: "demolition.ceiling_area_m2",
      workAreaType: "demolition",
      category: "measurement",
    },
    {
      key: "demolition.disposal_included",
      label: "Disposal",
      questionText: "Is waste removal/disposal included?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: true,
      priority: 20,
      factKey: "demolition.disposal_included",
      workAreaType: "demolition",
      category: "scope",
    },
    {
      key: "demolition.skip_bin_included",
      label: "Skip bin",
      questionText: "Is a skip bin included?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 21,
      factKey: "demolition.skip_bin_included",
      workAreaType: "demolition",
      category: "scope",
    },
    {
      key: "demolition.carting_distance_m",
      label: "Carting distance",
      questionText: "Approximate distance to cart waste to skip or disposal point?",
      inputType: "number",
      unit: "m",
      required: false,
      priority: 22,
      factKey: "demolition.carting_distance_m",
      workAreaType: "demolition",
      category: "measurement",
    },
    {
      key: "demolition.access",
      label: "Access",
      questionText: "How difficult is access for removal?",
      inputType: "select",
      options: ["Easy", "Moderate", "Poor", "Very poor", "Not sure"],
      required: false,
      priority: 30,
      factKey: "demolition.access",
      workAreaType: "demolition",
      category: "risk",
    },
    {
      key: "demolition.floor_level",
      label: "Floor level",
      questionText: "What floor level is the work on?",
      inputType: "select",
      options: ["Ground", "Upper floor", "Basement", "Not sure"],
      required: false,
      priority: 31,
      factKey: "demolition.floor_level",
      workAreaType: "demolition",
      category: "risk",
    },
    {
      key: "demolition.services_isolated",
      label: "Services isolated",
      questionText: "Are services isolated before demolition?",
      inputType: "select",
      options: ["Yes", "No", "By others", "Not sure"],
      required: false,
      priority: 40,
      factKey: "demolition.services_isolated",
      workAreaType: "demolition",
      category: "risk",
    },
    {
      key: "demolition.hazardous_materials_risk",
      label: "Hazardous materials risk",
      questionText: "Is there a hazardous materials risk?",
      inputType: "select",
      options: [
        "None known",
        "Possible asbestos",
        "Possible lead paint",
        "Possible mould",
        "Not sure",
      ],
      required: false,
      priority: 41,
      factKey: "demolition.hazardous_materials_risk",
      workAreaType: "demolition",
      category: "risk",
    },
    {
      key: "demolition.salvage_required",
      label: "Salvage required",
      questionText: "Is salvage of materials required?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 50,
      factKey: "demolition.salvage_required",
      workAreaType: "demolition",
      category: "scope",
    },
    {
      key: "demolition.noise_hours_restriction",
      label: "Noise/hours restriction",
      questionText: "Are there noise or working hours restrictions?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 51,
      factKey: "demolition.noise_hours_restriction",
      workAreaType: "demolition",
      category: "risk",
    },
  ],
};
