import type { ScopeDefinition } from "@/lib/scopes/types";

export const doorsScope: ScopeDefinition = {
  type: "doors",
  label: "Doors",
  questions: [
    {
      key: "doors.count",
      label: "Number of doors",
      questionText: "How many doors are included?",
      inputType: "number",
      unit: "doors",
      required: true,
      priority: 10,
      factKey: "doors.count",
      workAreaType: "doors",
      category: "measurement",
    },
    {
      key: "doors.door_type",
      label: "Door type",
      questionText: "What door type is required?",
      inputType: "select",
      options: [
        "Hollow core",
        "Solid core",
        "Fire rated",
        "Exterior",
        "Cavity slider",
        "Other",
        "Not sure",
      ],
      required: false,
      priority: 20,
      factKey: "doors.door_type",
      workAreaType: "doors",
      category: "scope",
    },
    {
      key: "doors.prehung",
      label: "Pre-hung doors",
      questionText: "Are doors pre-hung?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: true,
      priority: 30,
      factKey: "doors.prehung",
      workAreaType: "doors",
      category: "scope",
    },
    {
      key: "doors.frames_included",
      label: "Door frames",
      questionText: "Are door frames included?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: true,
      priority: 40,
      factKey: "doors.frames_included",
      workAreaType: "doors",
      category: "scope",
    },
    {
      key: "doors.hardware_install_included",
      label: "Hardware installation",
      questionText: "Is door hardware installation included?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: true,
      priority: 50,
      factKey: "doors.hardware_install_included",
      workAreaType: "doors",
      category: "scope",
    },
    {
      key: "doors.hardware_client_supplied",
      label: "Client-supplied hardware",
      questionText: "Is door hardware supplied by the client?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 55,
      factKey: "doors.hardware_client_supplied",
      workAreaType: "doors",
      category: "scope",
    },
    {
      key: "doors.painting_included",
      label: "Door painting",
      questionText: "Is door painting/finishing included?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 60,
      factKey: "doors.painting_included",
      workAreaType: "doors",
      category: "scope",
    },
  ],
};
