import type { ScopeDefinition } from "@/lib/scopes/types";

export const externalStairsScope: ScopeDefinition = {
  type: "external_stairs",
  label: "External Stairs",
  questions: [
    {
      key: "external_stairs.risers_count",
      label: "Number of risers",
      questionText: "Approximately how many risers are required?",
      inputType: "number",
      unit: "risers",
      required: false,
      priority: 10,
      factKey: "external_stairs.risers_count",
      workAreaType: "external_stairs",
      category: "measurement",
    },
    {
      key: "external_stairs.total_rise_m",
      label: "Total rise",
      questionText: "What is the total rise height?",
      inputType: "number",
      unit: "m",
      required: false,
      priority: 11,
      factKey: "external_stairs.total_rise_m",
      workAreaType: "external_stairs",
      category: "measurement",
    },
    {
      key: "external_stairs.width_m",
      label: "Stair width",
      questionText: "Approximate stair width?",
      inputType: "number",
      unit: "m",
      required: false,
      priority: 15,
      factKey: "external_stairs.width_m",
      workAreaType: "external_stairs",
      category: "measurement",
    },
    {
      key: "external_stairs.material",
      label: "Stair material",
      questionText: "What stair material should be allowed for?",
      inputType: "select",
      options: [
        "Treated timber",
        "Hardwood",
        "Steel",
        "Concrete",
        "Composite",
        "Other",
        "Not sure",
      ],
      required: false,
      priority: 20,
      factKey: "external_stairs.material",
      workAreaType: "external_stairs",
      category: "scope",
    },
    {
      key: "external_stairs.stringer_type",
      label: "Stringer type",
      questionText: "What stringer type is required?",
      inputType: "select",
      options: ["Timber", "Steel", "Other", "Not sure"],
      required: false,
      priority: 21,
      factKey: "external_stairs.stringer_type",
      workAreaType: "external_stairs",
      category: "scope",
    },
    {
      key: "external_stairs.landing_included",
      label: "Landing included",
      questionText: "Is a landing included?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 25,
      factKey: "external_stairs.landing_included",
      workAreaType: "external_stairs",
      category: "scope",
    },
    {
      key: "external_stairs.landing_area_m2",
      label: "Landing area",
      questionText: "Approximate landing area?",
      inputType: "number",
      unit: "m²",
      required: false,
      priority: 26,
      factKey: "external_stairs.landing_area_m2",
      workAreaType: "external_stairs",
      category: "measurement",
    },
    {
      key: "external_stairs.landings_count",
      label: "Number of landings",
      questionText: "Number of landings, if applicable?",
      inputType: "number",
      unit: "landings",
      required: false,
      priority: 27,
      factKey: "external_stairs.landings_count",
      workAreaType: "external_stairs",
      category: "measurement",
    },
    {
      key: "external_stairs.handrail_included",
      label: "Handrail",
      questionText: "Is a handrail included?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 30,
      factKey: "external_stairs.handrail_included",
      workAreaType: "external_stairs",
      category: "scope",
    },
    {
      key: "external_stairs.balustrade_included",
      label: "Balustrade",
      questionText: "Is a balustrade included?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 31,
      factKey: "external_stairs.balustrade_included",
      workAreaType: "external_stairs",
      category: "scope",
    },
    {
      key: "external_stairs.existing_removal",
      label: "Existing stair removal",
      questionText: "Is removal of existing stairs included?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 35,
      factKey: "external_stairs.existing_removal",
      workAreaType: "external_stairs",
      category: "scope",
    },
    {
      key: "external_stairs.access",
      label: "Access",
      questionText: "How difficult is site access?",
      inputType: "select",
      options: ["Easy", "Moderate", "Poor", "Not sure"],
      required: false,
      priority: 40,
      factKey: "external_stairs.access",
      workAreaType: "external_stairs",
      category: "risk",
    },
    {
      key: "external_stairs.ground_condition",
      label: "Ground condition",
      questionText: "What is the ground condition at the stair location?",
      inputType: "select",
      options: ["Level", "Sloping", "Uneven", "Not sure"],
      required: false,
      priority: 41,
      factKey: "external_stairs.ground_condition",
      workAreaType: "external_stairs",
      category: "risk",
    },
    {
      key: "external_stairs.consent_or_engineering_status",
      label: "Consent/engineering",
      questionText: "Is consent or engineering required?",
      inputType: "select",
      options: ["Not required", "Required", "Not sure"],
      required: false,
      priority: 42,
      factKey: "external_stairs.consent_or_engineering_status",
      workAreaType: "external_stairs",
      category: "risk",
    },
    {
      key: "external_stairs.finish_required",
      label: "Finish required",
      questionText: "Is a finish (paint/stain) required?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 50,
      factKey: "external_stairs.finish_required",
      workAreaType: "external_stairs",
      category: "scope",
    },
    {
      key: "external_stairs.finish_type",
      label: "Finish type",
      questionText: "What finish type is required?",
      inputType: "select",
      options: ["Paint", "Stain", "None", "Not sure"],
      required: false,
      priority: 51,
      factKey: "external_stairs.finish_type",
      workAreaType: "external_stairs",
      category: "scope",
    },
  ],
};
