import type { ScopeDefinition } from "@/lib/scopes/types";

export const externalStairsScope: ScopeDefinition = {
  type: "external_stairs",
  label: "External Stairs",
  questions: [
    {
      key: "external_stairs.risers_count",
      label: "Number of risers",
      questionText: "Approximately how many risers are required?",
      inputType: "number",
      unit: "risers",
      required: true,
      priority: 10,
      factKey: "external_stairs.risers_count",
      workAreaType: "external_stairs",
      category: "measurement",
    },
    {
      key: "external_stairs.landings_count",
      label: "Number of landings",
      questionText: "Number of landings, if applicable?",
      inputType: "number",
      unit: "landings",
      required: false,
      priority: 15,
      factKey: "external_stairs.landings_count",
      workAreaType: "external_stairs",
      category: "measurement",
    },
    {
      key: "external_stairs.material",
      label: "Stair material",
      questionText: "What stair material should be allowed for?",
      inputType: "select",
      options: [
        "Treated Pine",
        "Hardwood",
        "Steel",
        "Concrete",
        "Other",
        "Not sure",
      ],
      required: false,
      priority: 20,
      factKey: "external_stairs.material",
      workAreaType: "external_stairs",
      category: "scope",
    },
    {
      key: "external_stairs.width_m",
      label: "Stair width",
      questionText: "Approximate stair width?",
      inputType: "number",
      unit: "m",
      required: false,
      priority: 25,
      factKey: "external_stairs.width_m",
      workAreaType: "external_stairs",
      category: "measurement",
    },
    {
      key: "external_stairs.handrail_included",
      label: "Handrail",
      questionText: "Is a handrail included?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: true,
      priority: 30,
      factKey: "external_stairs.handrail_included",
      workAreaType: "external_stairs",
      category: "scope",
    },
  ],
};
