import type { ScopeDefinition } from "@/lib/scopes/types";
import { FENCE_SYSTEM_OPTIONS } from "@/lib/estimate/fence-systems";

export const fenceScope: ScopeDefinition = {
  type: "fence",
  label: "Fence",
  questions: [
    {
      key: "fence.system",
      label: "Fence type",
      questionText: "What type of fence is this?",
      inputType: "select",
      options: [...FENCE_SYSTEM_OPTIONS],
      required: true,
      priority: 5,
      estimatePriorityClass: "P0",
      level1BlockingClass: "HARD_MINIMUM",
      factKey: "fence.system",
      workAreaType: "fence",
      category: "scope",
    },
    {
      key: "fence.length_m",
      label: "Fence length",
      questionText: "What is the fence length?",
      inputType: "number",
      unit: "m",
      required: true,
      priority: 10,
      estimatePriorityClass: "P0",
      level1BlockingClass: "HARD_MINIMUM",
      factKey: "fence.length_m",
      workAreaType: "fence",
      category: "measurement",
    },
    {
      key: "fence.height_m",
      label: "Fence height",
      questionText: "What is the fence height?",
      inputType: "number",
      unit: "m",
      required: true,
      priority: 20,
      estimatePriorityClass: "P0",
      level1BlockingClass: "HARD_MINIMUM",
      factKey: "fence.height_m",
      workAreaType: "fence",
      category: "measurement",
    },
    {
      key: "fence.material",
      label: "Fence material",
      questionText: "What fence material should be allowed for?",
      inputType: "select",
      options: ["Timber", "Metal", "Composite", "Not sure"],
      required: false,
      priority: 30,
      estimatePriorityClass: "P1",
      factKey: "fence.material",
      workAreaType: "fence",
      category: "scope",
    },
    {
      key: "fence.timber_species",
      label: "Timber species",
      questionText: "What visible timber species?",
      inputType: "select",
      options: ["Radiata Pine", "Macrocarpa", "Cedar", "Hardwood"],
      required: false,
      priority: 31,
      estimatePriorityClass: "P1",
      factKey: "fence.timber_species",
      workAreaType: "fence",
      category: "scope",
    },
    {
      key: "fence.board_thickness_mm",
      label: "Board thickness",
      questionText: "Which board section?",
      inputType: "select",
      options: ["150 × 19mm", "150 × 25mm"],
      required: false,
      priority: 32,
      estimatePriorityClass: "P1",
      factKey: "fence.board_thickness_mm",
      workAreaType: "fence",
      category: "scope",
    },
    {
      key: "fence.slat_gap_mm",
      label: "Gap between horizontal boards/slats",
      questionText: "What gap between horizontal boards/slats?",
      inputType: "number",
      unit: "mm",
      required: false,
      priority: 33,
      estimatePriorityClass: "P1",
      factKey: "fence.slat_gap_mm",
      workAreaType: "fence",
      category: "measurement",
    },
    {
      key: "fence.vertical_paling_gap_mm",
      label: "Gap between vertical palings",
      questionText: "What gap between vertical palings?",
      inputType: "number",
      unit: "mm",
      required: false,
      priority: 45,
      estimatePriorityClass: "P2",
      factKey: "fence.vertical_paling_gap_mm",
      workAreaType: "fence",
      category: "measurement",
    },
    {
      key: "fence.horizontal_course_count",
      label: "Horizontal slat course count",
      questionText: "Override horizontal slat course count?",
      inputType: "number",
      required: false,
      priority: 44,
      estimatePriorityClass: "P3",
      factKey: "fence.horizontal_course_count",
      workAreaType: "fence",
      category: "measurement",
    },
    {
      key: "fence.top_capping",
      label: "Top capping",
      questionText: "Top capping included?",
      inputType: "select",
      options: ["Yes", "No", "Not sure if needed"],
      required: false,
      priority: 34,
      estimatePriorityClass: "P1",
      factKey: "fence.top_capping",
      workAreaType: "fence",
      category: "scope",
    },
    {
      key: "fence.post_spacing_m",
      label: "Post spacing",
      questionText: "What maximum post spacing should be allowed?",
      inputType: "number",
      unit: "m",
      required: false,
      priority: 35,
      estimatePriorityClass: "P2",
      factKey: "fence.post_spacing_m",
      workAreaType: "fence",
      category: "measurement",
    },
    {
      key: "fence.post_embedment_m",
      label: "Post embedment",
      questionText: "How deep are posts embedded?",
      inputType: "number",
      unit: "m",
      required: false,
      priority: 36,
      estimatePriorityClass: "P2",
      factKey: "fence.post_embedment_m",
      workAreaType: "fence",
      category: "measurement",
    },
    {
      key: "fence.hole_diameter_m",
      label: "Post-hole diameter",
      questionText: "What post-hole diameter?",
      inputType: "number",
      unit: "m",
      required: false,
      priority: 37,
      estimatePriorityClass: "P3",
      factKey: "fence.hole_diameter_m",
      workAreaType: "fence",
      category: "measurement",
    },
    {
      key: "fence.section_width_m",
      label: "Section width",
      questionText: "What modular section width?",
      inputType: "number",
      unit: "m",
      required: false,
      priority: 38,
      estimatePriorityClass: "P1",
      factKey: "fence.section_width_m",
      workAreaType: "fence",
      category: "measurement",
    },
    {
      key: "fence.section_count",
      label: "Section count",
      questionText: "How many fence sections if you already know?",
      inputType: "number",
      required: false,
      priority: 39,
      estimatePriorityClass: "P3",
      factKey: "fence.section_count",
      workAreaType: "fence",
      category: "measurement",
    },
    {
      key: "fence.metal_material",
      label: "Metal type",
      questionText: "Aluminium or steel slat fence?",
      inputType: "select",
      options: ["Aluminium", "Steel"],
      required: false,
      priority: 40,
      estimatePriorityClass: "P2",
      factKey: "fence.metal_material",
      workAreaType: "fence",
      category: "scope",
    },
    {
      key: "fence.paling_or_panel_type",
      label: "Paling or panel type",
      questionText: "Are palings or panels being used?",
      inputType: "select",
      options: ["Palings", "Panels", "Paling and rail", "Other", "Not sure"],
      required: false,
      priority: 41,
      estimatePriorityClass: "P3",
      factKey: "fence.paling_or_panel_type",
      workAreaType: "fence",
      category: "scope",
    },
    {
      key: "fence.rail_count",
      label: "Rail count",
      questionText: "How many horizontal rails if you want to override the estimate?",
      inputType: "number",
      required: false,
      priority: 42,
      estimatePriorityClass: "P3",
      factKey: "fence.rail_count",
      workAreaType: "fence",
      category: "measurement",
    },
    {
      key: "fence.rail_section",
      label: "Fence rail section",
      questionText: "What fence rail section?",
      inputType: "select",
      options: ["75 × 50mm H4", "100 × 50mm H4", "75 × 40mm H4"],
      required: false,
      priority: 43,
      estimatePriorityClass: "P3",
      factKey: "fence.rail_section",
      workAreaType: "fence",
      category: "scope",
    },
    {
      key: "fence.demolition_required",
      label: "Existing fence removal",
      questionText: "Is removal of an existing fence required?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 50,
      estimatePriorityClass: "P1",
      factKey: "fence.demolition_required",
      workAreaType: "fence",
      category: "scope",
    },
    {
      key: "fence.gate_included",
      label: "Gate",
      questionText: "Is a gate included?",
      inputType: "boolean",
      options: ["Yes", "No"],
      required: false,
      priority: 55,
      estimatePriorityClass: "P1",
      factKey: "fence.gate_included",
      workAreaType: "fence",
      category: "scope",
    },
    {
      key: "fence.gate_count",
      label: "Number of gates",
      questionText: "How many gates are included?",
      inputType: "number",
      required: false,
      priority: 56,
      estimatePriorityClass: "P1",
      factKey: "fence.gate_count",
      workAreaType: "fence",
      category: "measurement",
    },
    {
      key: "fence.gate_width_m",
      label: "Gate width",
      questionText: "Approximate gate width?",
      inputType: "number",
      unit: "m",
      required: false,
      priority: 57,
      estimatePriorityClass: "P1",
      factKey: "fence.gate_width_m",
      workAreaType: "fence",
      category: "measurement",
    },
    {
      key: "fence.gate_position",
      label: "Gate position",
      questionText: "Where is the gate along the fence?",
      inputType: "select",
      options: ["At an end", "Within the fence run", "Not sure"],
      required: false,
      priority: 58,
      estimatePriorityClass: "P2",
      factKey: "fence.gate_position",
      workAreaType: "fence",
      category: "scope",
    },
    {
      key: "fence.gate_capping",
      label: "Gate matches fence capping",
      questionText: "Does the gate match the fence top capping?",
      inputType: "select",
      options: ["Yes", "No"],
      required: false,
      priority: 59,
      estimatePriorityClass: "P2",
      factKey: "fence.gate_capping",
      workAreaType: "fence",
      category: "scope",
    },
    {
      key: "fence.slope_condition",
      label: "Ground profile",
      questionText: "What is the ground profile along the fence line?",
      inputType: "select",
      options: ["Level", "Sloping / stepped", "Not sure"],
      required: false,
      priority: 60,
      estimatePriorityClass: "P2",
      factKey: "fence.slope_condition",
      workAreaType: "fence",
      category: "risk",
    },
    {
      key: "fence.corner_count",
      label: "Number of corners",
      questionText: "How many corners if this is not one straight run?",
      inputType: "number",
      required: false,
      priority: 61,
      estimatePriorityClass: "P3",
      factKey: "fence.corner_count",
      workAreaType: "fence",
      category: "measurement",
    },
    {
      key: "fence.disposal_required",
      label: "Disposal allowance",
      questionText: "Is disposal of removed fencing included?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 65,
      estimatePriorityClass: "P2",
      factKey: "fence.disposal_required",
      workAreaType: "fence",
      category: "allowance",
    },
    {
      key: "fence.boundary_approval_status",
      label: "Boundary approval",
      questionText: "Is neighbour or boundary approval confirmed?",
      inputType: "select",
      options: ["Confirmed", "Pending", "Not required", "Not sure"],
      required: false,
      priority: 70,
      estimatePriorityClass: "P3",
      factKey: "fence.boundary_approval_status",
      workAreaType: "fence",
      category: "risk",
    },
    {
      key: "fence.services_risk",
      label: "Services risk",
      questionText: "Are underground services a known risk along the fence line?",
      inputType: "select",
      options: ["No known risk", "Possible risk", "Known services", "Not sure"],
      required: false,
      priority: 75,
      estimatePriorityClass: "P3",
      factKey: "fence.services_risk",
      workAreaType: "fence",
      category: "risk",
    },
    {
      key: "fence.finish_required",
      label: "Painting/staining",
      questionText: "Is painting or staining included?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 80,
      estimatePriorityClass: "P3",
      factKey: "fence.finish_required",
      workAreaType: "fence",
      category: "scope",
    },
    {
      key: "fence.finish_type",
      label: "Fence finish type",
      questionText: "Paint, stain, or clear coat?",
      inputType: "select",
      options: ["paint", "stain", "clear_coat", "other", "unknown"],
      required: false,
      priority: 81,
      estimatePriorityClass: "P3",
      factKey: "fence.finish_type",
      workAreaType: "fence",
      category: "scope",
    },
    {
      key: "fence.finish_sides",
      label: "Finish sides",
      questionText: "One side or both sides?",
      inputType: "select",
      options: ["one_side", "both_sides", "unknown"],
      required: false,
      priority: 82,
      estimatePriorityClass: "P3",
      factKey: "fence.finish_sides",
      workAreaType: "fence",
      category: "scope",
    },
  ],
};
