import type { ScopeDefinition } from "@/lib/scopes/types";

export const fenceScope: ScopeDefinition = {
  type: "fence",
  label: "Fence",
  questions: [
    {
      key: "fence.length_m",
      label: "Fence length",
      questionText: "What is the fence length?",
      inputType: "number",
      unit: "m",
      required: true,
      priority: 10,
      factKey: "fence.length_m",
      workAreaType: "fence",
      category: "measurement",
    },
    {
      key: "fence.height_m",
      label: "Fence height",
      questionText: "What is the fence height?",
      inputType: "number",
      unit: "m",
      required: true,
      priority: 20,
      factKey: "fence.height_m",
      workAreaType: "fence",
      category: "measurement",
    },
    {
      key: "fence.material",
      label: "Fence material",
      questionText: "What fence material should be allowed for?",
      inputType: "select",
      options: ["Timber", "Metal", "Composite", "Not sure"],
      required: true,
      priority: 30,
      factKey: "fence.material",
      workAreaType: "fence",
      category: "scope",
    },
    {
      key: "fence.gate_included",
      label: "Gate",
      questionText: "Is a gate included?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 40,
      factKey: "fence.gate_included",
      workAreaType: "fence",
      category: "scope",
    },
    {
      key: "fence.demolition_required",
      label: "Existing fence removal",
      questionText: "Is removal of an existing fence required?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 50,
      factKey: "fence.demolition_required",
      workAreaType: "fence",
      category: "scope",
    },
  ],
};
