import type { ScopeDefinition } from "@/lib/scopes/types";

export const fenceScope: ScopeDefinition = {
  type: "fence",
  label: "Fence",
  questions: [
    {
      key: "fence.length_m",
      label: "Fence length",
      questionText: "What is the fence length?",
      inputType: "number",
      unit: "m",
      required: true,
      priority: 10,
      factKey: "fence.length_m",
      workAreaType: "fence",
      category: "measurement",
    },
    {
      key: "fence.height_m",
      label: "Fence height",
      questionText: "What is the fence height?",
      inputType: "number",
      unit: "m",
      required: true,
      priority: 20,
      factKey: "fence.height_m",
      workAreaType: "fence",
      category: "measurement",
    },
    {
      key: "fence.material",
      label: "Fence material",
      questionText: "What fence material should be allowed for?",
      inputType: "select",
      options: ["Timber", "Metal", "Composite", "Not sure"],
      required: true,
      priority: 30,
      factKey: "fence.material",
      workAreaType: "fence",
      category: "scope",
    },
    {
      key: "fence.demolition_required",
      label: "Existing fence removal",
      questionText: "Is removal of an existing fence required?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 40,
      factKey: "fence.demolition_required",
      workAreaType: "fence",
      category: "scope",
    },
    {
      key: "fence.access",
      label: "Access difficulty",
      questionText: "How difficult is site access for this fence?",
      inputType: "select",
      options: ["Easy", "Moderate", "Difficult", "Not sure"],
      required: false,
      priority: 45,
      factKey: "fence.access",
      workAreaType: "fence",
      category: "risk",
    },
    {
      key: "fence.gate_included",
      label: "Gate",
      questionText: "Is a gate included?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 50,
      factKey: "fence.gate_included",
      workAreaType: "fence",
      category: "scope",
    },
    {
      key: "fence.gate_count",
      label: "Number of gates",
      questionText: "How many gates are included?",
      inputType: "number",
      required: false,
      priority: 51,
      factKey: "fence.gate_count",
      workAreaType: "fence",
      category: "measurement",
    },
    {
      key: "fence.slope_condition",
      label: "Ground slope",
      questionText: "Is the fence line on sloping or uneven ground?",
      inputType: "select",
      options: [
        "Flat/even",
        "Moderate slope",
        "Steep/sloping",
        "Not sure",
      ],
      required: false,
      priority: 55,
      factKey: "fence.slope_condition",
      workAreaType: "fence",
      category: "risk",
    },
    {
      key: "fence.disposal_required",
      label: "Disposal allowance",
      questionText: "Is disposal of removed fencing included?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 60,
      factKey: "fence.disposal_required",
      workAreaType: "fence",
      category: "allowance",
    },
    {
      key: "fence.boundary_approval_status",
      label: "Boundary approval",
      questionText: "Is neighbour or boundary approval confirmed?",
      inputType: "select",
      options: [
        "Confirmed",
        "Pending",
        "Not required",
        "Not sure",
      ],
      required: false,
      priority: 65,
      factKey: "fence.boundary_approval_status",
      workAreaType: "fence",
      category: "risk",
    },
    {
      key: "fence.services_risk",
      label: "Services risk",
      questionText: "Are underground services a known risk along the fence line?",
      inputType: "select",
      options: ["No known risk", "Possible risk", "Known services", "Not sure"],
      required: false,
      priority: 70,
      factKey: "fence.services_risk",
      workAreaType: "fence",
      category: "risk",
    },
    {
      key: "fence.finish_required",
      label: "Painting/staining",
      questionText: "Is painting or staining included for the fence?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 75,
      factKey: "fence.finish_required",
      workAreaType: "fence",
      category: "scope",
    },
    {
      key: "fence.finish_type",
      label: "Fence finish type",
      questionText: "What finish is included?",
      inputType: "select",
      options: ["paint", "stain", "clear_coat", "other", "unknown"],
      required: false,
      priority: 76,
      factKey: "fence.finish_type",
      workAreaType: "fence",
      category: "scope",
    },
    {
      key: "fence.finish_sides",
      label: "Finish sides",
      questionText: "How many sides are included?",
      inputType: "select",
      options: ["one_side", "both_sides", "unknown"],
      required: false,
      priority: 77,
      factKey: "fence.finish_sides",
      workAreaType: "fence",
      category: "scope",
    },
  ],
};
