import type { ScopeDefinition } from "@/lib/scopes/types";

export const flooringScope: ScopeDefinition = {
  type: "flooring",
  label: "Flooring",
  questions: [
    {
      key: "flooring.area_m2",
      label: "Flooring area",
      questionText: "What is the approximate flooring area?",
      inputType: "number",
      unit: "m²",
      required: true,
      priority: 10,
      factKey: "flooring.area_m2",
      workAreaType: "flooring",
      category: "measurement",
    },
    {
      key: "flooring.type",
      label: "Flooring type",
      questionText: "What type of flooring is required?",
      inputType: "select",
      options: [
        "Vinyl",
        "Carpet",
        "Hardwood",
        "Laminate",
        "Engineered timber",
        "Tile",
        "Other",
        "Not sure",
      ],
      required: true,
      priority: 20,
      factKey: "flooring.type",
      workAreaType: "flooring",
      category: "scope",
    },
    {
      key: "flooring.existing_flooring_removal",
      label: "Existing flooring removal",
      questionText: "Are you replacing/removing existing flooring?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: true,
      priority: 30,
      factKey: "flooring.existing_flooring_removal",
      workAreaType: "flooring",
      category: "scope",
    },
    {
      key: "flooring.floor_prep_level",
      label: "Floor preparation",
      questionText: "What level of floor preparation is required?",
      inputType: "select",
      options: ["None", "Minor", "Moderate", "Major", "Not sure"],
      required: false,
      priority: 40,
      factKey: "flooring.floor_prep_level",
      workAreaType: "flooring",
      category: "scope",
    },
    {
      key: "flooring.subfloor_replacement_required",
      label: "Subfloor replacement",
      questionText: "Is underlying flooring/subfloor replacement required?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 45,
      factKey: "flooring.subfloor_replacement_required",
      workAreaType: "flooring",
      category: "risk",
    },
    {
      key: "flooring.stairs_or_landings_included",
      label: "Stairs or landings",
      questionText: "Are stairs or landings included in the flooring scope?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 50,
      factKey: "flooring.stairs_or_landings_included",
      workAreaType: "flooring",
      category: "scope",
    },
    {
      key: "flooring.stair_count",
      label: "Stair count",
      questionText: "How many stairs are included?",
      inputType: "number",
      unit: "stairs",
      required: false,
      priority: 51,
      factKey: "flooring.stair_count",
      workAreaType: "flooring",
      category: "measurement",
    },
    {
      key: "flooring.landing_area_m2",
      label: "Landing area",
      questionText: "Approximate landing area?",
      inputType: "number",
      unit: "m²",
      required: false,
      priority: 52,
      factKey: "flooring.landing_area_m2",
      workAreaType: "flooring",
      category: "measurement",
    },
  ],
};
