import type { ScopeDefinition } from "@/lib/scopes/types";

export const internalWallsScope: ScopeDefinition = {
  type: "internal_walls",
  label: "Internal walls",
  questions: [
    {
      key: "internal_walls.length_lm",
      label: "Wall length",
      questionText: "What is the total wall length?",
      inputType: "number",
      unit: "lm",
      required: true,
      priority: 10,
      factKey: "internal_walls.length_lm",
      workAreaType: "internal_walls",
      category: "measurement",
    },
    {
      key: "internal_walls.height_m",
      label: "Wall height",
      questionText: "What is the wall height?",
      inputType: "number",
      unit: "m",
      required: true,
      priority: 20,
      factKey: "internal_walls.height_m",
      workAreaType: "internal_walls",
      category: "measurement",
    },
    {
      key: "internal_walls.framing_type",
      label: "Framing type",
      questionText: "What framing type is required?",
      inputType: "select",
      options: [
        "Timber",
        "Steel stud",
        "Existing frame",
        "Other",
        "Not sure",
      ],
      required: false,
      priority: 30,
      factKey: "internal_walls.framing_type",
      workAreaType: "internal_walls",
      category: "scope",
    },
    {
      key: "internal_walls.wall_lining_type",
      label: "Wall lining",
      questionText: "What wall lining is required?",
      inputType: "select",
      options: [
        "Plasterboard",
        "Plywood",
        "Fibre cement",
        "Other",
        "Not sure",
      ],
      required: true,
      priority: 40,
      factKey: "internal_walls.wall_lining_type",
      workAreaType: "internal_walls",
      category: "scope",
    },
    {
      key: "internal_walls.plasterboard_type",
      label: "Plasterboard type",
      questionText: "What plasterboard type is required?",
      inputType: "select",
      options: [
        "Standard",
        "Fyreline",
        "Braceline",
        "Aqualine",
        "Noise control",
        "Other",
        "Not sure",
      ],
      required: true,
      priority: 45,
      factKey: "internal_walls.plasterboard_type",
      workAreaType: "internal_walls",
      category: "scope",
    },
    {
      key: "internal_walls.lining_sides",
      label: "Lining sides",
      questionText: "Is lining required on one side or both sides?",
      inputType: "select",
      options: ["One side", "Both sides", "Not sure"],
      required: true,
      priority: 50,
      factKey: "internal_walls.lining_sides",
      workAreaType: "internal_walls",
      category: "scope",
    },
    {
      key: "internal_walls.skirtings_included",
      label: "Skirtings",
      questionText: "Are skirtings included?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 55,
      factKey: "internal_walls.skirtings_included",
      workAreaType: "internal_walls",
      category: "scope",
    },
    {
      key: "internal_walls.skirting_length_lm",
      label: "Skirting length",
      questionText: "Approximate skirting length?",
      inputType: "number",
      unit: "lm",
      required: false,
      priority: 56,
      factKey: "internal_walls.skirting_length_lm",
      workAreaType: "internal_walls",
      category: "measurement",
    },
    {
      key: "internal_walls.insulation_included",
      label: "Insulation",
      questionText: "Is wall insulation included?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 60,
      factKey: "internal_walls.insulation_included",
      workAreaType: "internal_walls",
      category: "scope",
    },
  ],
};
