import type { ScopeDefinition } from "@/lib/scopes/types";
import {
  INTERNAL_WALLS_JOB_SCOPE_FACT_KEY,
  INTERNAL_WALLS_JOB_SCOPE_OPTIONS,
  INTERNAL_WALLS_STRUCTURAL_FACT_KEY,
  INTERNAL_WALLS_STRUCTURAL_OPTIONS,
} from "@/lib/estimate/internal-walls-scope";
import {
  INTERNAL_WALLS_FRAME_SYSTEM_OPTIONS,
  INTERNAL_WALLS_LAYER_OPTIONS,
  INTERNAL_WALLS_LINING_PRODUCT_OPTIONS,
  INTERNAL_WALLS_SAME_BOTH_SIDES_OPTIONS,
  INTERNAL_WALLS_SHEET_LENGTH_OPTIONS,
  INTERNAL_WALLS_STUD_CENTRES_OPTIONS,
  INTERNAL_WALLS_THICKNESS_OPTIONS,
  INTERNAL_WALLS_TIMBER_SIZE_OPTIONS,
} from "@/lib/estimate/internal-walls-wall-types";

export const internalWallsScope: ScopeDefinition = {
  type: "internal_walls",
  label: "Internal walls",
  questions: [
    {
      key: INTERNAL_WALLS_JOB_SCOPE_FACT_KEY,
      label: "Wall work",
      questionText: "What wall work are you doing?",
      inputType: "select",
      options: [...INTERNAL_WALLS_JOB_SCOPE_OPTIONS],
      required: true,
      priority: 5,
      estimatePriorityClass: "P0",
      level1BlockingClass: "HARD_MINIMUM",
      factKey: INTERNAL_WALLS_JOB_SCOPE_FACT_KEY,
      workAreaType: "internal_walls",
      category: "scope",
    },
    {
      key: INTERNAL_WALLS_STRUCTURAL_FACT_KEY,
      label: "Load-bearing or structural",
      questionText: "Could this wall be load-bearing or structural?",
      inputType: "select",
      options: [...INTERNAL_WALLS_STRUCTURAL_OPTIONS],
      required: true,
      priority: 6,
      estimatePriorityClass: "P0",
      level1BlockingClass: "HARD_MINIMUM",
      factKey: INTERNAL_WALLS_STRUCTURAL_FACT_KEY,
      workAreaType: "internal_walls",
      category: "risk",
    },
    {
      key: "internal_walls.wall_type.frame_system",
      label: "Framing",
      questionText: "What framing is this wall type?",
      inputType: "select",
      options: [...INTERNAL_WALLS_FRAME_SYSTEM_OPTIONS],
      required: true,
      priority: 12,
      estimatePriorityClass: "P0",
      level1BlockingClass: "HARD_MINIMUM",
      factKey: "internal_walls.wall_type.frame_system",
      workAreaType: "internal_walls",
      category: "scope",
    },
    {
      key: "internal_walls.wall_type.frame_size",
      label: "Timber framing size",
      questionText: "What timber framing size is this wall type?",
      inputType: "select",
      options: [...INTERNAL_WALLS_TIMBER_SIZE_OPTIONS],
      required: false,
      priority: 13,
      estimatePriorityClass: "P0",
      level1BlockingClass: "HARD_MINIMUM",
      factKey: "internal_walls.wall_type.frame_size",
      workAreaType: "internal_walls",
      category: "scope",
    },
    {
      key: "internal_walls.wall_type.length_lm",
      label: "Total wall length",
      questionText: "What is the total wall length for this wall type?",
      inputType: "number",
      unit: "lm",
      required: true,
      priority: 14,
      estimatePriorityClass: "P0",
      level1BlockingClass: "HARD_MINIMUM",
      factKey: "internal_walls.wall_type.length_lm",
      workAreaType: "internal_walls",
      category: "measurement",
    },
    {
      key: "internal_walls.wall_type.height_m",
      label: "Wall height",
      questionText: "What is the wall height for this wall type?",
      inputType: "number",
      unit: "m",
      required: false,
      priority: 15,
      estimatePriorityClass: "P0",
      level1BlockingClass: "ASSUMABLE",
      factKey: "internal_walls.wall_type.height_m",
      workAreaType: "internal_walls",
      category: "measurement",
    },
    {
      key: "internal_walls.wall_type.stud_centres_mm",
      label: "Stud spacing",
      questionText: "What stud spacing do you want? Recommended spacing is shown.",
      inputType: "select",
      options: [...INTERNAL_WALLS_STUD_CENTRES_OPTIONS],
      required: false,
      priority: 16,
      estimatePriorityClass: "P0",
      level1BlockingClass: "ASSUMABLE",
      factKey: "internal_walls.wall_type.stud_centres_mm",
      workAreaType: "internal_walls",
      category: "scope",
    },
    {
      key: "internal_walls.wall_type.side_a_product",
      label: "Side A lining",
      questionText: "What lining is on Side A?",
      inputType: "select",
      options: [...INTERNAL_WALLS_LINING_PRODUCT_OPTIONS],
      required: false,
      priority: 17,
      estimatePriorityClass: "P0",
      factKey: "internal_walls.wall_type.side_a_product",
      workAreaType: "internal_walls",
      category: "finish",
    },
    {
      key: "internal_walls.wall_type.side_a_thickness_mm",
      label: "Side A thickness",
      questionText: "What lining thickness is on Side A?",
      inputType: "select",
      options: [...INTERNAL_WALLS_THICKNESS_OPTIONS],
      required: false,
      priority: 17.2,
      estimatePriorityClass: "P1",
      factKey: "internal_walls.wall_type.side_a_thickness_mm",
      workAreaType: "internal_walls",
      category: "finish",
    },
    {
      key: "internal_walls.wall_type.side_a_sheet_length_mm",
      label: "Sheet length",
      questionText:
        "What sheet length? Recommended length is the smallest validated product length that spans the wall height.",
      inputType: "select",
      options: [...INTERNAL_WALLS_SHEET_LENGTH_OPTIONS],
      required: false,
      priority: 17.5,
      estimatePriorityClass: "P0",
      factKey: "internal_walls.wall_type.side_a_sheet_length_mm",
      workAreaType: "internal_walls",
      category: "finish",
    },
    {
      key: "internal_walls.wall_type.side_a_layers",
      label: "Side A layers",
      questionText: "How many lining layers on Side A?",
      inputType: "select",
      options: [...INTERNAL_WALLS_LAYER_OPTIONS],
      required: false,
      priority: 18,
      estimatePriorityClass: "P1",
      factKey: "internal_walls.wall_type.side_a_layers",
      workAreaType: "internal_walls",
      category: "finish",
    },
    {
      key: "internal_walls.wall_type.same_lining_both_sides",
      label: "Same lining both sides",
      questionText: "Same lining both sides?",
      inputType: "select",
      options: [...INTERNAL_WALLS_SAME_BOTH_SIDES_OPTIONS],
      required: false,
      priority: 19,
      estimatePriorityClass: "P0",
      factKey: "internal_walls.wall_type.same_lining_both_sides",
      workAreaType: "internal_walls",
      category: "finish",
    },
    {
      key: "internal_walls.wall_type.side_b_product",
      label: "Side B lining",
      questionText: "What lining is on Side B?",
      inputType: "select",
      options: [...INTERNAL_WALLS_LINING_PRODUCT_OPTIONS],
      required: false,
      priority: 21,
      estimatePriorityClass: "P0",
      factKey: "internal_walls.wall_type.side_b_product",
      workAreaType: "internal_walls",
      category: "finish",
    },
    {
      key: "internal_walls.wall_type.side_b_thickness_mm",
      label: "Side B thickness",
      questionText: "What lining thickness is on Side B?",
      inputType: "select",
      options: [...INTERNAL_WALLS_THICKNESS_OPTIONS],
      required: false,
      priority: 21.2,
      estimatePriorityClass: "P1",
      factKey: "internal_walls.wall_type.side_b_thickness_mm",
      workAreaType: "internal_walls",
      category: "finish",
    },
    {
      key: "internal_walls.wall_type.side_b_sheet_length_mm",
      label: "Side B sheet length",
      questionText:
        "What sheet length on Side B? Product-specific availability is not yet confirmed.",
      inputType: "select",
      options: [...INTERNAL_WALLS_SHEET_LENGTH_OPTIONS],
      required: false,
      priority: 21.5,
      estimatePriorityClass: "P1",
      factKey: "internal_walls.wall_type.side_b_sheet_length_mm",
      workAreaType: "internal_walls",
      category: "finish",
    },
    {
      key: "internal_walls.wall_type.side_b_layers",
      label: "Side B layers",
      questionText: "How many lining layers on Side B?",
      inputType: "select",
      options: [...INTERNAL_WALLS_LAYER_OPTIONS],
      required: false,
      priority: 22,
      estimatePriorityClass: "P1",
      factKey: "internal_walls.wall_type.side_b_layers",
      workAreaType: "internal_walls",
      category: "finish",
    },
    {
      key: "internal_walls.wall_type.label",
      label: "Wall type name",
      questionText: "Optional name for this wall type? (for example Office partitions)",
      inputType: "text",
      required: false,
      priority: 11,
      estimatePriorityClass: "P2",
      factKey: "internal_walls.wall_type.label",
      workAreaType: "internal_walls",
      category: "scope",
    },
    {
      key: "internal_walls.length_lm",
      label: "Wall length",
      questionText: "What is the total wall length?",
      inputType: "number",
      unit: "lm",
      required: true,
      priority: 30,
      factKey: "internal_walls.length_lm",
      workAreaType: "internal_walls",
      category: "measurement",
    },
    {
      key: "internal_walls.height_m",
      label: "Wall height",
      questionText: "What is the wall height?",
      inputType: "number",
      unit: "m",
      required: true,
      priority: 31,
      factKey: "internal_walls.height_m",
      workAreaType: "internal_walls",
      category: "measurement",
    },
    {
      key: "internal_walls.framing_type",
      label: "Framing type",
      questionText: "What framing type is required?",
      inputType: "select",
      options: [
        "Timber",
        "Steel stud",
        "Existing frame",
        "Other",
        "Not sure",
      ],
      required: true,
      priority: 32,
      factKey: "internal_walls.framing_type",
      workAreaType: "internal_walls",
      category: "scope",
    },
    {
      key: "internal_walls.wall_lining_type",
      label: "Wall lining",
      questionText: "What wall lining is required?",
      inputType: "select",
      options: [
        "Plasterboard",
        "Plywood",
        "Fibre cement",
        "Other",
        "Not sure",
      ],
      required: true,
      priority: 40,
      factKey: "internal_walls.wall_lining_type",
      workAreaType: "internal_walls",
      category: "scope",
    },
    {
      key: "internal_walls.plasterboard_type",
      label: "Plasterboard type",
      questionText: "What plasterboard type is required?",
      inputType: "select",
      options: [
        "Standard",
        "Fyreline",
        "Braceline",
        "Aqualine",
        "Noise control",
        "Other",
        "Not sure",
      ],
      required: true,
      priority: 45,
      factKey: "internal_walls.plasterboard_type",
      workAreaType: "internal_walls",
      category: "scope",
    },
    {
      key: "internal_walls.lining_sides",
      label: "Lining sides",
      questionText: "Is lining required on one side or both sides?",
      inputType: "select",
      options: ["One side", "Both sides", "Not sure"],
      required: true,
      priority: 50,
      factKey: "internal_walls.lining_sides",
      workAreaType: "internal_walls",
      category: "scope",
    },
    {
      key: "internal_walls.fire_or_acoustic",
      label: "Fire or acoustic rating",
      questionText: "Is fire or acoustic rating required?",
      inputType: "select",
      options: [
        "None",
        "Fire-rated",
        "Acoustic",
        "Fire and acoustic",
        "Not sure",
      ],
      required: false,
      priority: 52,
      factKey: "internal_walls.fire_or_acoustic",
      workAreaType: "internal_walls",
      category: "scope",
    },
    {
      key: "internal_walls.skirtings_included",
      label: "Skirtings",
      questionText: "Are skirtings included?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 55,
      factKey: "internal_walls.skirtings_included",
      workAreaType: "internal_walls",
      category: "scope",
    },
    {
      key: "internal_walls.skirting_length_lm",
      label: "Skirting length",
      questionText: "Approximate skirting length?",
      inputType: "number",
      unit: "lm",
      required: false,
      priority: 56,
      factKey: "internal_walls.skirting_length_lm",
      workAreaType: "internal_walls",
      category: "measurement",
    },
    {
      key: "internal_walls.demolition_included",
      label: "Demolition",
      questionText: "Is demolition/removal of existing wall included?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 35,
      factKey: "internal_walls.demolition_included",
      workAreaType: "internal_walls",
      category: "scope",
    },
    {
      key: "internal_walls.stopping_included",
      label: "Stopping/plastering",
      questionText: "Is stopping/plastering included?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 57,
      factKey: "internal_walls.stopping_included",
      workAreaType: "internal_walls",
      category: "scope",
    },
    {
      key: "internal_walls.painting_included",
      label: "Painting",
      questionText: "Is painting included?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 58,
      factKey: "internal_walls.painting_included",
      workAreaType: "internal_walls",
      category: "scope",
    },
    {
      key: "internal_walls.insulation_included",
      label: "Insulation",
      questionText: "Is wall insulation included?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 60,
      factKey: "internal_walls.insulation_included",
      workAreaType: "internal_walls",
      category: "scope",
    },
  ],
};
