import type { ScopeDefinition } from "@/lib/scopes/types";

export const kitchenScope: ScopeDefinition = {
  type: "kitchen",
  label: "Kitchen renovation",
  questions: [
    {
      key: "kitchen.area_m2",
      label: "Kitchen area",
      questionText: "What is the approximate kitchen area?",
      inputType: "number",
      unit: "m²",
      required: true,
      priority: 10,
      factKey: "kitchen.area_m2",
      workAreaType: "kitchen",
      category: "measurement",
    },
    {
      key: "kitchen.renovation_type",
      label: "Renovation type",
      questionText: "What type of kitchen scope is this?",
      inputType: "select",
      options: [
        "Install only",
        "Replace like-for-like",
        "Full kitchen renovation",
        "Not sure",
      ],
      required: true,
      priority: 15,
      factKey: "kitchen.renovation_type",
      workAreaType: "kitchen",
      category: "scope",
    },
    {
      key: "kitchen.finish_level",
      label: "Finish level",
      questionText: "What finish level should be allowed for this kitchen?",
      inputType: "select",
      options: ["Budget", "Standard", "Premium", "Not sure"],
      required: true,
      priority: 20,
      factKey: "kitchen.finish_level",
      workAreaType: "kitchen",
      category: "finish",
    },
    {
      key: "kitchen.demolition_required",
      label: "Demolition",
      questionText: "Is demolition/strip-out included?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: true,
      priority: 30,
      factKey: "kitchen.demolition_required",
      workAreaType: "kitchen",
      category: "scope",
    },
    {
      key: "kitchen.flooring_included",
      label: "Kitchen flooring",
      questionText: "Is flooring included in the kitchen scope?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: true,
      priority: 35,
      factKey: "kitchen.flooring_included",
      workAreaType: "kitchen",
      category: "scope",
    },
    {
      key: "kitchen.flooring_area_m2",
      label: "Kitchen flooring area",
      questionText: "Approximate kitchen flooring area?",
      inputType: "number",
      unit: "m²",
      required: false,
      priority: 36,
      factKey: "kitchen.flooring_area_m2",
      workAreaType: "kitchen",
      category: "measurement",
    },
    {
      key: "kitchen.flooring_type",
      label: "Kitchen flooring type",
      questionText: "What type of kitchen flooring is included?",
      inputType: "select",
      options: [
        "Vinyl",
        "Tile",
        "Hardwood",
        "Laminate",
        "Engineered timber",
        "Other",
        "Not sure",
      ],
      required: false,
      priority: 37,
      factKey: "kitchen.flooring_type",
      workAreaType: "kitchen",
      category: "scope",
    },
    {
      key: "kitchen.cabinetry_included",
      label: "Cabinetry",
      questionText: "Is cabinetry included?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 60,
      factKey: "kitchen.cabinetry_included",
      workAreaType: "kitchen",
      category: "scope",
    },
    {
      key: "kitchen.island_included",
      label: "Island",
      questionText: "Is a kitchen island included?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 59,
      factKey: "kitchen.island_included",
      workAreaType: "kitchen",
      category: "scope",
    },
    {
      key: "kitchen.island_length_m",
      label: "Island length",
      questionText: "Approximate island length?",
      inputType: "number",
      unit: "m",
      required: false,
      priority: 59.5,
      factKey: "kitchen.island_length_m",
      workAreaType: "kitchen",
      category: "measurement",
    },
    {
      key: "kitchen.cabinetry_lm",
      label: "Cabinetry length",
      questionText: "Approximate linear metres of cabinetry?",
      inputType: "number",
      unit: "lm",
      required: false,
      priority: 60.5,
      factKey: "kitchen.cabinetry_lm",
      workAreaType: "kitchen",
      category: "measurement",
    },
    {
      key: "kitchen.benchtop_included",
      label: "Benchtop",
      questionText: "Is a benchtop included?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 65,
      factKey: "kitchen.benchtop_included",
      workAreaType: "kitchen",
      category: "scope",
    },
    {
      key: "kitchen.benchtop_material",
      label: "Benchtop material",
      questionText: "What benchtop material is included?",
      inputType: "select",
      options: [
        "Laminate",
        "Timber",
        "Stone / engineered",
        "Stainless",
        "Other",
        "Not sure",
      ],
      required: false,
      priority: 66,
      factKey: "kitchen.benchtop_material",
      workAreaType: "kitchen",
      category: "scope",
    },
    {
      key: "kitchen.appliances_included",
      label: "Appliances",
      questionText: "Are appliances included?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 68,
      factKey: "kitchen.appliances_included",
      workAreaType: "kitchen",
      category: "scope",
    },
    {
      key: "kitchen.cabinetry_client_supplied",
      label: "Client-supplied cabinetry",
      questionText: "Is cabinetry client supplied?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 61,
      factKey: "kitchen.cabinetry_client_supplied",
      workAreaType: "kitchen",
      category: "scope",
    },
    {
      key: "kitchen.cabinetry_type",
      label: "Cabinetry type",
      questionText: "What type of cabinetry is included?",
      inputType: "select",
      options: ["Flatpack", "Custom", "Not sure"],
      required: false,
      priority: 62,
      factKey: "kitchen.cabinetry_type",
      workAreaType: "kitchen",
      category: "scope",
    },
    {
      key: "kitchen.splashback_included",
      label: "Splashback",
      questionText: "Is a splashback included?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 63,
      factKey: "kitchen.splashback_included",
      workAreaType: "kitchen",
      category: "scope",
    },
    {
      key: "kitchen.splashback_area_m2",
      label: "Splashback area",
      questionText: "Approximate splashback area?",
      inputType: "number",
      unit: "m²",
      required: false,
      priority: 64,
      factKey: "kitchen.splashback_area_m2",
      workAreaType: "kitchen",
      category: "measurement",
    },
    {
      key: "kitchen.rangehood_included",
      label: "Rangehood",
      questionText: "Is a rangehood/venting included?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 67,
      factKey: "kitchen.rangehood_included",
      workAreaType: "kitchen",
      category: "scope",
    },
    {
      key: "kitchen.appliances_client_supplied",
      label: "Client-supplied appliances",
      questionText: "Are appliances client supplied?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 69,
      factKey: "kitchen.appliances_client_supplied",
      workAreaType: "kitchen",
      category: "scope",
    },
    {
      key: "kitchen.plumbing_changes",
      label: "Plumbing changes",
      questionText: "What level of plumbing changes are included?",
      inputType: "select",
      options: ["None", "Minor", "Major", "Not sure"],
      required: false,
      priority: 70,
      factKey: "kitchen.plumbing_changes",
      workAreaType: "kitchen",
      category: "scope",
    },
    {
      key: "kitchen.electrical_changes",
      label: "Electrical changes",
      questionText: "What level of electrical changes are included?",
      inputType: "select",
      options: ["None", "Minor", "Major", "Not sure"],
      required: false,
      priority: 75,
      factKey: "kitchen.electrical_changes",
      workAreaType: "kitchen",
      category: "scope",
    },
  ],
};
