import type { ScopeDefinition } from "@/lib/scopes/types";

export const kitchenScope: ScopeDefinition = {
  type: "kitchen",
  label: "Kitchen renovation",
  questions: [
    {
      key: "kitchen.area_m2",
      label: "Kitchen area",
      questionText: "What is the approximate kitchen area?",
      inputType: "number",
      unit: "m²",
      required: true,
      priority: 10,
      factKey: "kitchen.area_m2",
      workAreaType: "kitchen",
      category: "measurement",
    },
    {
      key: "kitchen.finish_level",
      label: "Finish level",
      questionText: "What finish level should be allowed for this kitchen?",
      inputType: "select",
      options: ["Budget", "Standard", "Premium", "Not sure"],
      required: true,
      priority: 20,
      factKey: "kitchen.finish_level",
      workAreaType: "kitchen",
      category: "finish",
    },
    {
      key: "kitchen.demolition_required",
      label: "Demolition",
      questionText: "Is demolition/strip-out included?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: true,
      priority: 30,
      factKey: "kitchen.demolition_required",
      workAreaType: "kitchen",
      category: "scope",
    },
    {
      key: "kitchen.flooring_included",
      label: "Kitchen flooring",
      questionText: "Is flooring included in the kitchen scope?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: true,
      priority: 35,
      factKey: "kitchen.flooring_included",
      workAreaType: "kitchen",
      category: "scope",
    },
    {
      key: "kitchen.flooring_area_m2",
      label: "Kitchen flooring area",
      questionText: "Approximate kitchen flooring area?",
      inputType: "number",
      unit: "m²",
      required: false,
      priority: 36,
      factKey: "kitchen.flooring_area_m2",
      workAreaType: "kitchen",
      category: "measurement",
    },
    {
      key: "kitchen.flooring_type",
      label: "Kitchen flooring type",
      questionText: "What type of kitchen flooring is included?",
      inputType: "select",
      options: [
        "Vinyl",
        "Tile",
        "Hardwood",
        "Laminate",
        "Engineered timber",
        "Other",
        "Not sure",
      ],
      required: false,
      priority: 37,
      factKey: "kitchen.flooring_type",
      workAreaType: "kitchen",
      category: "scope",
    },
    {
      key: "kitchen.cabinetry_included",
      label: "Cabinetry",
      questionText: "Is cabinetry included in this estimate?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 60,
      factKey: "kitchen.cabinetry_included",
      workAreaType: "kitchen",
      category: "scope",
    },
    {
      key: "kitchen.benchtop_included",
      label: "Benchtop",
      questionText: "Is a benchtop included in this estimate?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 65,
      factKey: "kitchen.benchtop_included",
      workAreaType: "kitchen",
      category: "scope",
    },
    {
      key: "kitchen.appliances_included",
      label: "Appliances",
      questionText: "Are appliances included in this estimate?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 68,
      factKey: "kitchen.appliances_included",
      workAreaType: "kitchen",
      category: "scope",
    },
    {
      key: "kitchen.plumbing_changes",
      label: "Plumbing changes",
      questionText: "What level of plumbing changes are included?",
      inputType: "select",
      options: ["None", "Minor", "Major", "Not sure"],
      required: false,
      priority: 70,
      factKey: "kitchen.plumbing_changes",
      workAreaType: "kitchen",
      category: "scope",
    },
    {
      key: "kitchen.electrical_changes",
      label: "Electrical changes",
      questionText: "What level of electrical changes are included?",
      inputType: "select",
      options: ["None", "Minor", "Major", "Not sure"],
      required: false,
      priority: 75,
      factKey: "kitchen.electrical_changes",
      workAreaType: "kitchen",
      category: "scope",
    },
  ],
};
