import type { ScopeDefinition } from "@/lib/scopes/types";

export const kitchenScope: ScopeDefinition = {
  type: "kitchen",
  label: "Kitchen renovation",
  questions: [
    {
      key: "kitchen.area_m2",
      label: "Kitchen area",
      questionText: "What is the approximate kitchen area?",
      inputType: "number",
      unit: "m²",
      required: true,
      priority: 10,
      factKey: "kitchen.area_m2",
      workAreaType: "kitchen",
      category: "measurement",
    },
    {
      key: "kitchen.finish_level",
      label: "Finish level",
      questionText: "What finish level should be allowed for this kitchen?",
      inputType: "select",
      options: ["Budget", "Standard", "Premium", "Not sure"],
      required: true,
      priority: 20,
      factKey: "kitchen.finish_level",
      workAreaType: "kitchen",
      category: "finish",
    },
    {
      key: "kitchen.demolition_required",
      label: "Demolition",
      questionText: "Is demolition/strip-out included?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: true,
      priority: 30,
      factKey: "kitchen.demolition_required",
      workAreaType: "kitchen",
      category: "scope",
    },
    {
      key: "kitchen.plumbing_required",
      label: "Plumbing",
      questionText: "Should plumbing work be allowed for?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 40,
      factKey: "kitchen.plumbing_required",
      workAreaType: "kitchen",
      category: "scope",
    },
    {
      key: "kitchen.electrical_required",
      label: "Electrical",
      questionText: "Should electrical work be allowed for?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 50,
      factKey: "kitchen.electrical_required",
      workAreaType: "kitchen",
      category: "scope",
    },
    {
      key: "kitchen.cabinetry_included",
      label: "Cabinetry",
      questionText: "Is cabinetry included in this estimate?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 60,
      factKey: "kitchen.cabinetry_included",
      workAreaType: "kitchen",
      category: "scope",
    },
    {
      key: "kitchen.benchtop_included",
      label: "Benchtop",
      questionText: "Is a benchtop included in this estimate?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 65,
      factKey: "kitchen.benchtop_included",
      workAreaType: "kitchen",
      category: "scope",
    },
  ],
};
