import type { ScopeDefinition } from "@/lib/scopes/types";

export const paintingScope: ScopeDefinition = {
  type: "painting",
  label: "Painting",
  questions: [
    {
      key: "painting.location",
      label: "Painting location",
      questionText: "Is painting internal, external or both?",
      inputType: "select",
      options: ["Internal", "External", "Both", "Not sure"],
      required: true,
      priority: 10,
      factKey: "painting.location",
      workAreaType: "painting",
      category: "scope",
    },
    {
      key: "painting.internal_area_m2",
      label: "Internal painting area",
      questionText: "Approximate internal painting area?",
      inputType: "number",
      unit: "m²",
      required: true,
      priority: 20,
      factKey: "painting.internal_area_m2",
      workAreaType: "painting",
      category: "measurement",
    },
    {
      key: "painting.external_area_m2",
      label: "External painting area",
      questionText: "Approximate external painting area?",
      inputType: "number",
      unit: "m²",
      required: true,
      priority: 25,
      factKey: "painting.external_area_m2",
      workAreaType: "painting",
      category: "measurement",
    },
    {
      key: "painting.coats_required",
      label: "Number of coats",
      questionText: "How many coats are required?",
      inputType: "select",
      options: ["1", "2", "3", "Not sure"],
      required: true,
      priority: 30,
      factKey: "painting.coats_required",
      workAreaType: "painting",
      category: "scope",
    },
    {
      key: "painting.prep_level",
      label: "Prep level",
      questionText: "What level of surface preparation is required?",
      inputType: "select",
      options: ["Light", "Standard", "Heavy", "Not sure"],
      required: false,
      priority: 40,
      factKey: "painting.prep_level",
      workAreaType: "painting",
      category: "scope",
    },
    {
      key: "painting.door_painting_included",
      label: "Door painting",
      questionText: "Is door painting included?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 50,
      factKey: "painting.door_painting_included",
      workAreaType: "painting",
      category: "scope",
    },
    {
      key: "painting.door_count",
      label: "Doors to paint",
      questionText: "How many doors are included in painting?",
      inputType: "number",
      unit: "doors",
      required: false,
      priority: 51,
      factKey: "painting.door_count",
      workAreaType: "painting",
      category: "measurement",
    },
    {
      key: "painting.joinery_surround_painting_required",
      label: "Joinery surround painting",
      questionText: "Is joinery surround painting required?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 55,
      factKey: "painting.joinery_surround_painting_required",
      workAreaType: "painting",
      category: "scope",
    },
    {
      key: "painting.joinery_surround_length_lm",
      label: "Joinery surround length",
      questionText: "Approximate joinery surround length to paint?",
      inputType: "number",
      unit: "lm",
      required: false,
      priority: 56,
      factKey: "painting.joinery_surround_length_lm",
      workAreaType: "painting",
      category: "measurement",
    },
    {
      key: "painting.paint_client_supplied",
      label: "Client-supplied paint",
      questionText: "Is paint supplied by the client?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 60,
      factKey: "painting.paint_client_supplied",
      workAreaType: "painting",
      category: "scope",
    },
  ],
};
