import type { ScopeDefinition } from "@/lib/scopes/types";

export const pergolaScope: ScopeDefinition = {
  type: "pergola",
  label: "Pergola",
  questions: [
    {
      key: "pergola.length_m",
      label: "Pergola length",
      questionText: "What is the pergola length?",
      inputType: "number",
      unit: "m",
      required: false,
      priority: 8,
      factKey: "pergola.length_m",
      workAreaType: "pergola",
      category: "measurement",
    },
    {
      key: "pergola.width_m",
      label: "Pergola width",
      questionText: "What is the pergola width?",
      inputType: "number",
      unit: "m",
      required: false,
      priority: 9,
      factKey: "pergola.width_m",
      workAreaType: "pergola",
      category: "measurement",
    },
    {
      key: "pergola.area_m2",
      label: "Pergola area",
      questionText: "What is the approximate pergola area?",
      inputType: "number",
      unit: "m²",
      required: true,
      priority: 10,
      factKey: "pergola.area_m2",
      workAreaType: "pergola",
      category: "measurement",
    },
    {
      key: "pergola.material",
      label: "Pergola material",
      questionText: "What pergola material should be allowed for?",
      inputType: "select",
      options: ["Timber", "Steel", "Aluminium", "Not sure"],
      required: true,
      priority: 20,
      factKey: "pergola.material",
      workAreaType: "pergola",
      category: "scope",
    },
    {
      key: "pergola.attached",
      label: "Attachment",
      questionText: "Is the pergola attached to the house or free-standing?",
      inputType: "select",
      options: ["Attached", "Free-standing", "Not sure"],
      required: true,
      priority: 25,
      factKey: "pergola.attached",
      workAreaType: "pergola",
      category: "scope",
    },
    {
      key: "pergola.roofing_included",
      label: "Roofing/covering",
      questionText: "Is roofing or covering included?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 30,
      factKey: "pergola.roofing_included",
      workAreaType: "pergola",
      category: "scope",
    },
    {
      key: "pergola.roofing_type",
      label: "Roofing type",
      questionText: "What type of roof or covering is included?",
      inputType: "select",
      options: [
        "Colorsteel",
        "Polycarbonate",
        "Timber slats",
        "Other",
        "Not sure",
      ],
      required: false,
      priority: 31,
      factKey: "pergola.roofing_type",
      workAreaType: "pergola",
      category: "scope",
    },
    {
      key: "pergola.access",
      label: "Access difficulty",
      questionText: "How difficult is site access for this pergola?",
      inputType: "select",
      options: ["Easy", "Moderate", "Difficult", "Not sure"],
      required: false,
      priority: 35,
      factKey: "pergola.access",
      workAreaType: "pergola",
      category: "risk",
    },
    {
      key: "pergola.footings_required",
      label: "Footings/posts",
      questionText: "Are post footings or concrete pads required?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 40,
      factKey: "pergola.footings_required",
      workAreaType: "pergola",
      category: "scope",
    },
    {
      key: "pergola.gutters_included",
      label: "Gutters/drainage",
      questionText: "Are gutters or drainage included?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 45,
      factKey: "pergola.gutters_included",
      workAreaType: "pergola",
      category: "scope",
    },
    {
      key: "pergola.tie_in_existing",
      label: "Tie-in to existing",
      questionText: "Does the pergola tie into existing structure?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 50,
      factKey: "pergola.tie_in_existing",
      workAreaType: "pergola",
      category: "scope",
    },
    {
      key: "pergola.engineering_or_consent_status",
      label: "Engineering/consent",
      questionText: "Is engineering or building consent required?",
      inputType: "select",
      options: ["Not required", "Required", "Not sure"],
      required: false,
      priority: 55,
      factKey: "pergola.engineering_or_consent_status",
      workAreaType: "pergola",
      category: "risk",
    },
    {
      key: "pergola.finish_required",
      label: "Painting/staining",
      questionText:
        "Is painting, staining or finishing included for the pergola?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 58,
      factKey: "pergola.finish_required",
      workAreaType: "pergola",
      category: "scope",
    },
    {
      key: "pergola.finish_type",
      label: "Pergola finish type",
      questionText: "What finish is included?",
      inputType: "select",
      options: [
        "paint",
        "stain",
        "clear_coat",
        "powdercoated_material",
        "other",
        "unknown",
      ],
      required: false,
      priority: 59,
      factKey: "pergola.finish_type",
      workAreaType: "pergola",
      category: "scope",
    },
  ],
};
