import type { ScopeDefinition } from "@/lib/scopes/types";

export const pergolaScope: ScopeDefinition = {
  type: "pergola",
  label: "Pergola",
  questions: [
    {
      key: "pergola.area_m2",
      label: "Pergola area",
      questionText: "What is the approximate pergola area?",
      inputType: "number",
      unit: "m²",
      required: true,
      priority: 10,
      factKey: "pergola.area_m2",
      workAreaType: "pergola",
      category: "measurement",
    },
    {
      key: "pergola.material",
      label: "Pergola material",
      questionText: "What pergola material should be allowed for?",
      inputType: "select",
      options: ["Timber", "Steel", "Aluminium", "Not sure"],
      required: false,
      priority: 20,
      factKey: "pergola.material",
      workAreaType: "pergola",
      category: "scope",
    },
    {
      key: "pergola.roofing_included",
      label: "Roofing/covering",
      questionText: "Is roofing or covering included?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 30,
      factKey: "pergola.roofing_included",
      workAreaType: "pergola",
      category: "scope",
    },
    {
      key: "pergola.attached",
      label: "Attachment",
      questionText: "Is the pergola attached to the house or free-standing?",
      inputType: "select",
      options: ["Attached", "Free-standing", "Not sure"],
      required: false,
      priority: 40,
      factKey: "pergola.attached",
      workAreaType: "pergola",
      category: "scope",
    },
  ],
};
