import type { ScopeDefinition } from "@/lib/scopes/types";

export const plasteringScope: ScopeDefinition = {
  type: "plastering",
  label: "Plastering",
  questions: [
    {
      key: "plastering.area_m2",
      label: "Plastering area",
      questionText: "Approximate plastering area?",
      inputType: "number",
      unit: "m²",
      required: true,
      priority: 10,
      factKey: "plastering.area_m2",
      workAreaType: "plastering",
      category: "measurement",
    },
    {
      key: "plastering.level",
      label: "Plastering level",
      questionText: "What level of plastering is required?",
      inputType: "select",
      options: [
        "Level 3",
        "Level 4",
        "Level 5",
        "Patching only",
        "Not sure",
      ],
      required: true,
      priority: 20,
      factKey: "plastering.level",
      workAreaType: "plastering",
      category: "scope",
    },
    {
      key: "plastering.surface_type",
      label: "Surface type",
      questionText: "Is this new plasterboard or an existing surface?",
      inputType: "select",
      options: [
        "New plasterboard",
        "Existing surface",
        "Patch repairs",
        "Mixed",
        "Not sure",
      ],
      required: false,
      priority: 30,
      factKey: "plastering.surface_type",
      workAreaType: "plastering",
      category: "scope",
    },
    {
      key: "plastering.complexity",
      label: "Stopping complexity",
      questionText: "What is the corners/stopping complexity?",
      inputType: "select",
      options: ["Simple", "Standard", "Complex", "Not sure"],
      required: false,
      priority: 40,
      factKey: "plastering.complexity",
      workAreaType: "plastering",
      category: "scope",
    },
    {
      key: "plastering.sanding_included",
      label: "Sanding included",
      questionText: "Is sanding included?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 50,
      factKey: "plastering.sanding_included",
      workAreaType: "plastering",
      category: "scope",
    },
  ],
};
