import type { ScopeDefinition } from "@/lib/scopes/types";

export const retainingWallScope: ScopeDefinition = {
  type: "retaining_wall",
  label: "Retaining wall",
  questions: [
    {
      key: "retaining_wall.length_m",
      label: "Wall length",
      questionText: "What is the retaining wall length?",
      inputType: "number",
      unit: "m",
      required: true,
      priority: 10,
      factKey: "retaining_wall.length_m",
      workAreaType: "retaining_wall",
      category: "measurement",
    },
    {
      key: "retaining_wall.height_m",
      label: "Wall height",
      questionText: "What is the average wall height?",
      inputType: "number",
      unit: "m",
      required: true,
      priority: 20,
      factKey: "retaining_wall.height_m",
      workAreaType: "retaining_wall",
      category: "measurement",
    },
    {
      key: "retaining_wall.material",
      label: "Wall material",
      questionText: "What retaining wall material should be allowed for?",
      inputType: "select",
      options: ["Timber", "Concrete", "Block", "Not sure"],
      required: true,
      priority: 30,
      factKey: "retaining_wall.material",
      workAreaType: "retaining_wall",
      category: "scope",
    },
    {
      key: "retaining_wall.drainage_required",
      label: "Drainage",
      questionText: "Should drainage be included behind the wall?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: true,
      priority: 40,
      factKey: "retaining_wall.drainage_required",
      workAreaType: "retaining_wall",
      category: "scope",
    },
    {
      key: "retaining_wall.excavation_required",
      label: "Excavation",
      questionText: "Is excavation required?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 50,
      factKey: "retaining_wall.excavation_required",
      workAreaType: "retaining_wall",
      category: "scope",
    },
    {
      key: "retaining_wall.carting_distance_m",
      label: "Carting distance",
      questionText: "Approximate carting distance for spoil/materials?",
      inputType: "number",
      unit: "m",
      required: false,
      priority: 60,
      factKey: "retaining_wall.carting_distance_m",
      workAreaType: "retaining_wall",
      category: "measurement",
    },
    {
      key: "retaining_wall.access",
      label: "Access",
      questionText: "How difficult is access for machinery/materials?",
      inputType: "select",
      options: ["Easy", "Moderate", "Difficult", "Not sure"],
      required: false,
      priority: 70,
      factKey: "retaining_wall.access",
      workAreaType: "retaining_wall",
      category: "risk",
    },
    {
      key: "retaining_wall.backfill_included",
      label: "Backfill",
      questionText: "Is backfilling included behind the wall?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 75,
      factKey: "retaining_wall.backfill_included",
      workAreaType: "retaining_wall",
      category: "scope",
    },
  ],
};
