import type { ScopeDefinition } from "@/lib/scopes/types";

export const retainingWallScope: ScopeDefinition = {
  type: "retaining_wall",
  label: "Retaining wall",
  questions: [
    {
      key: "retaining_wall.length_m",
      label: "Wall length",
      questionText: "What is the retaining wall length?",
      inputType: "number",
      unit: "m",
      required: true,
      priority: 10,
      factKey: "retaining_wall.length_m",
      workAreaType: "retaining_wall",
      category: "measurement",
    },
    {
      key: "retaining_wall.is_raking",
      label: "Raking wall",
      questionText: "Is one end of the retaining wall higher than the other?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 15,
      factKey: "retaining_wall.is_raking",
      workAreaType: "retaining_wall",
      category: "scope",
    },
    {
      key: "retaining_wall.height_m",
      label: "Wall height",
      questionText: "What is the average wall height?",
      inputType: "number",
      unit: "m",
      required: true,
      priority: 20,
      factKey: "retaining_wall.height_m",
      workAreaType: "retaining_wall",
      category: "measurement",
    },
    {
      key: "retaining_wall.height_high_m",
      label: "Height at high end",
      questionText: "Height at the high end of the wall?",
      inputType: "number",
      unit: "m",
      required: true,
      priority: 21,
      factKey: "retaining_wall.height_high_m",
      workAreaType: "retaining_wall",
      category: "measurement",
    },
    {
      key: "retaining_wall.height_low_m",
      label: "Height at low end",
      questionText: "Height at the low end of the wall?",
      inputType: "number",
      unit: "m",
      required: true,
      priority: 22,
      factKey: "retaining_wall.height_low_m",
      workAreaType: "retaining_wall",
      category: "measurement",
    },
    {
      key: "retaining_wall.fixing_type",
      label: "Wall fixing type",
      questionText: "Is the wall face-fixed or standard/post-and-rail?",
      inputType: "select",
      options: ["Standard", "Face-fixed", "Other", "Not sure"],
      required: true,
      priority: 30,
      factKey: "retaining_wall.fixing_type",
      workAreaType: "retaining_wall",
      category: "scope",
    },
    {
      key: "retaining_wall.material",
      label: "Wall material",
      questionText: "What retaining wall material should be allowed for?",
      inputType: "select",
      options: ["Timber", "Concrete sleeper", "Masonry / block", "Concrete", "Not sure"],
      required: true,
      priority: 32,
      factKey: "retaining_wall.material",
      workAreaType: "retaining_wall",
      category: "scope",
    },
    {
      key: "retaining_wall.drainage_required",
      label: "Drainage",
      questionText: "Should drainage be included behind the wall?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: true,
      priority: 40,
      factKey: "retaining_wall.drainage_required",
      workAreaType: "retaining_wall",
      category: "scope",
    },
    {
      key: "retaining_wall.drain_connection_required",
      label: "Drain connection",
      questionText:
        "Does retaining wall drainage need to connect to a cesspit or proper drain?",
      inputType: "select",
      options: [
        "No",
        "Cesspit required",
        "Connect to existing drain",
        "Not sure",
      ],
      required: false,
      priority: 42,
      factKey: "retaining_wall.drain_connection_required",
      workAreaType: "retaining_wall",
      category: "scope",
    },
    {
      key: "retaining_wall.backfill_included",
      label: "Backfill",
      questionText: "Is backfilling included behind the wall?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 50,
      factKey: "retaining_wall.backfill_included",
      workAreaType: "retaining_wall",
      category: "scope",
    },
    {
      key: "retaining_wall.backfill_length_m",
      label: "Backfill length",
      questionText: "Backfill length?",
      inputType: "number",
      unit: "m",
      required: false,
      priority: 51,
      factKey: "retaining_wall.backfill_length_m",
      workAreaType: "retaining_wall",
      category: "measurement",
    },
    {
      key: "retaining_wall.backfill_height_m",
      label: "Backfill height",
      questionText: "Approximate backfill height?",
      inputType: "number",
      unit: "m",
      required: false,
      priority: 52,
      factKey: "retaining_wall.backfill_height_m",
      workAreaType: "retaining_wall",
      category: "measurement",
    },
    {
      key: "retaining_wall.backfill_depth_m",
      label: "Backfill depth",
      questionText: "Approximate backfill depth behind wall?",
      inputType: "number",
      unit: "m",
      required: false,
      priority: 53,
      factKey: "retaining_wall.backfill_depth_m",
      workAreaType: "retaining_wall",
      category: "measurement",
    },
    {
      key: "retaining_wall.excavation_required",
      label: "Excavation",
      questionText: "Is excavation required?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 55,
      factKey: "retaining_wall.excavation_required",
      workAreaType: "retaining_wall",
      category: "scope",
    },
    {
      key: "retaining_wall.post_spacing_m",
      label: "Post spacing",
      questionText: "What post spacing should be allowed?",
      inputType: "number",
      unit: "m",
      required: false,
      priority: 34,
      factKey: "retaining_wall.post_spacing_m",
      workAreaType: "retaining_wall",
      category: "measurement",
    },
    {
      key: "retaining_wall.disposal_included",
      label: "Spoil removal",
      questionText: "Will excavated spoil need to be removed from site?",
      inputType: "boolean",
      options: [
        "No — spoil will remain or be reused on site",
        "Yes — some or all will be removed",
        "Not sure",
      ],
      required: false,
      priority: 56,
      factKey: "retaining_wall.disposal_included",
      workAreaType: "retaining_wall",
      category: "scope",
    },
    {
      key: "retaining_wall.spoil_removal_portion",
      label: "Spoil leaving site",
      questionText: "How much of the excavated material needs to leave site?",
      inputType: "select",
      options: ["All", "Some", "None"],
      required: false,
      priority: 58,
      factKey: "retaining_wall.spoil_removal_portion",
      workAreaType: "retaining_wall",
      category: "scope",
    },
    {
      key: "retaining_wall.spoil_removal_volume_m3",
      label: "Spoil removal volume",
      questionText: "Estimated spoil removal volume (m³)?",
      inputType: "number",
      unit: "m3",
      required: false,
      priority: 59,
      factKey: "retaining_wall.spoil_removal_volume_m3",
      workAreaType: "retaining_wall",
      category: "measurement",
    },
    {
      key: "retaining_wall.engineering_or_consent_status",
      label: "Engineering/consent",
      questionText: "Is engineering or consent required?",
      inputType: "select",
      options: ["Not required", "Required", "Not sure"],
      required: false,
      priority: 70,
      factKey: "retaining_wall.engineering_or_consent_status",
      workAreaType: "retaining_wall",
      category: "risk",
    },
    {
      key: "retaining_wall.surcharge",
      label: "Surcharge",
      questionText: "Does the wall support an additional load / surcharge?",
      inputType: "select",
      options: [
        "No",
        "Driveway / vehicle loading",
        "Parking",
        "Building / structure",
        "Another retaining wall",
        "Sloping ground above",
        "Other",
        "Not sure",
      ],
      required: false,
      priority: 36,
      factKey: "retaining_wall.surcharge",
      workAreaType: "retaining_wall",
      category: "scope",
    },
    {
      key: "retaining_wall.excavation_volume_m3",
      label: "Excavation volume",
      questionText: "Known bulk excavation volume, if supplied?",
      inputType: "number",
      unit: "m3",
      required: false,
      priority: 57,
      factKey: "retaining_wall.excavation_volume_m3",
      workAreaType: "retaining_wall",
      category: "measurement",
    },
    {
      key: "retaining_wall.face_board_section",
      label: "Face boards",
      questionText: "Which timber face-board section?",
      inputType: "select",
      options: ["150×50 H4", "200×50 H4"],
      required: false,
      priority: 80,
      factKey: "retaining_wall.face_board_section",
      workAreaType: "retaining_wall",
      category: "scope",
    },
    {
      key: "retaining_wall.sleeper_length_m",
      label: "Sleeper length",
      questionText: "Selected sleeper length?",
      inputType: "number",
      unit: "m",
      required: false,
      priority: 81,
      factKey: "retaining_wall.sleeper_length_m",
      workAreaType: "retaining_wall",
      category: "scope",
    },
    {
      key: "retaining_wall.sleeper_face_height_m",
      label: "Sleeper face height",
      questionText: "Selected sleeper face height?",
      inputType: "number",
      unit: "m",
      required: false,
      priority: 82,
      factKey: "retaining_wall.sleeper_face_height_m",
      workAreaType: "retaining_wall",
      category: "scope",
    },
    {
      key: "retaining_wall.block_series",
      label: "Block series",
      questionText: "Which masonry block series?",
      inputType: "select",
      options: ["150-series", "200-series"],
      required: false,
      priority: 83,
      factKey: "retaining_wall.block_series",
      workAreaType: "retaining_wall",
      category: "scope",
    },
    {
      key: "retaining_wall.block_laying_method",
      label: "Block laying",
      questionText: "Self-perform or subcontract block laying?",
      inputType: "select",
      options: ["Self-perform", "Subcontract"],
      required: false,
      priority: 84,
      factKey: "retaining_wall.block_laying_method",
      workAreaType: "retaining_wall",
      category: "scope",
    },
    {
      key: "retaining_wall.waterproofing_required",
      label: "Waterproofing",
      questionText: "Include waterproofing behind the masonry wall?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 38,
      factKey: "retaining_wall.waterproofing_required",
      workAreaType: "retaining_wall",
      category: "scope",
    },
    {
      key: "retaining_wall.waterproofing_type",
      label: "Waterproofing type",
      questionText: "Liquid or sheet membrane?",
      inputType: "select",
      options: ["Liquid membrane", "Sheet membrane"],
      required: false,
      priority: 85,
      factKey: "retaining_wall.waterproofing_type",
      workAreaType: "retaining_wall",
      category: "scope",
    },
    {
      key: "retaining_wall.pile_embedment_m",
      label: "Pile embedment",
      questionText: "Design pile embedment depth, if known?",
      inputType: "number",
      unit: "m",
      required: false,
      priority: 86,
      factKey: "retaining_wall.pile_embedment_m",
      workAreaType: "retaining_wall",
      category: "scope",
    },
    {
      key: "retaining_wall.horizontal_rebar_runs",
      label: "Horizontal rebar runs",
      questionText: "How many horizontal reinforcement runs if specified?",
      inputType: "number",
      required: false,
      priority: 87,
      factKey: "retaining_wall.horizontal_rebar_runs",
      workAreaType: "retaining_wall",
      category: "scope",
    },
  ],
};
