import type { ScopeDefinition } from "@/lib/scopes/types";

export const retainingWallScope: ScopeDefinition = {
  type: "retaining_wall",
  label: "Retaining wall",
  questions: [
    {
      key: "retaining_wall.length_m",
      label: "Wall length",
      questionText: "What is the retaining wall length?",
      inputType: "number",
      unit: "m",
      required: true,
      priority: 10,
      factKey: "retaining_wall.length_m",
      workAreaType: "retaining_wall",
      category: "measurement",
    },
    {
      key: "retaining_wall.is_raking",
      label: "Raking wall",
      questionText: "Is one end of the retaining wall higher than the other?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: true,
      priority: 15,
      factKey: "retaining_wall.is_raking",
      workAreaType: "retaining_wall",
      category: "scope",
    },
    {
      key: "retaining_wall.height_m",
      label: "Wall height",
      questionText: "What is the average wall height?",
      inputType: "number",
      unit: "m",
      required: true,
      priority: 20,
      factKey: "retaining_wall.height_m",
      workAreaType: "retaining_wall",
      category: "measurement",
    },
    {
      key: "retaining_wall.height_high_m",
      label: "Height at high end",
      questionText: "Height at the high end of the wall?",
      inputType: "number",
      unit: "m",
      required: true,
      priority: 21,
      factKey: "retaining_wall.height_high_m",
      workAreaType: "retaining_wall",
      category: "measurement",
    },
    {
      key: "retaining_wall.height_low_m",
      label: "Height at low end",
      questionText: "Height at the low end of the wall?",
      inputType: "number",
      unit: "m",
      required: true,
      priority: 22,
      factKey: "retaining_wall.height_low_m",
      workAreaType: "retaining_wall",
      category: "measurement",
    },
    {
      key: "retaining_wall.fixing_type",
      label: "Wall fixing type",
      questionText: "Is the wall face-fixed or standard/post-and-rail?",
      inputType: "select",
      options: ["Standard", "Face-fixed", "Other", "Not sure"],
      required: true,
      priority: 30,
      factKey: "retaining_wall.fixing_type",
      workAreaType: "retaining_wall",
      category: "scope",
    },
    {
      key: "retaining_wall.material",
      label: "Wall material",
      questionText: "What retaining wall material should be allowed for?",
      inputType: "select",
      options: ["Timber", "Concrete", "Block", "Not sure"],
      required: true,
      priority: 32,
      factKey: "retaining_wall.material",
      workAreaType: "retaining_wall",
      category: "scope",
    },
    {
      key: "retaining_wall.drainage_required",
      label: "Drainage",
      questionText: "Should drainage be included behind the wall?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: true,
      priority: 40,
      factKey: "retaining_wall.drainage_required",
      workAreaType: "retaining_wall",
      category: "scope",
    },
    {
      key: "retaining_wall.drain_connection_required",
      label: "Drain connection",
      questionText:
        "Does retaining wall drainage need to connect to a cesspit or proper drain?",
      inputType: "select",
      options: [
        "No",
        "Cesspit required",
        "Connect to existing drain",
        "Not sure",
      ],
      required: false,
      priority: 42,
      factKey: "retaining_wall.drain_connection_required",
      workAreaType: "retaining_wall",
      category: "scope",
    },
    {
      key: "retaining_wall.backfill_included",
      label: "Backfill",
      questionText: "Is backfilling included behind the wall?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 50,
      factKey: "retaining_wall.backfill_included",
      workAreaType: "retaining_wall",
      category: "scope",
    },
    {
      key: "retaining_wall.backfill_length_m",
      label: "Backfill length",
      questionText: "Backfill length?",
      inputType: "number",
      unit: "m",
      required: false,
      priority: 51,
      factKey: "retaining_wall.backfill_length_m",
      workAreaType: "retaining_wall",
      category: "measurement",
    },
    {
      key: "retaining_wall.backfill_height_m",
      label: "Backfill height",
      questionText: "Approximate backfill height?",
      inputType: "number",
      unit: "m",
      required: false,
      priority: 52,
      factKey: "retaining_wall.backfill_height_m",
      workAreaType: "retaining_wall",
      category: "measurement",
    },
    {
      key: "retaining_wall.backfill_depth_m",
      label: "Backfill depth",
      questionText: "Approximate backfill depth behind wall?",
      inputType: "number",
      unit: "m",
      required: false,
      priority: 53,
      factKey: "retaining_wall.backfill_depth_m",
      workAreaType: "retaining_wall",
      category: "measurement",
    },
    {
      key: "retaining_wall.excavation_required",
      label: "Excavation",
      questionText: "Is excavation required?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 55,
      factKey: "retaining_wall.excavation_required",
      workAreaType: "retaining_wall",
      category: "scope",
    },
    {
      key: "retaining_wall.disposal_included",
      label: "Disposal included",
      questionText: "Is spoil/disposal included?",
      inputType: "boolean",
      options: ["Yes", "No", "Not sure"],
      required: false,
      priority: 56,
      factKey: "retaining_wall.disposal_included",
      workAreaType: "retaining_wall",
      category: "scope",
    },
    {
      key: "retaining_wall.carting_distance_m",
      label: "Carting distance",
      questionText: "Approximate carting distance for spoil/materials?",
      inputType: "number",
      unit: "m",
      required: false,
      priority: 60,
      factKey: "retaining_wall.carting_distance_m",
      workAreaType: "retaining_wall",
      category: "measurement",
    },
    {
      key: "retaining_wall.engineering_or_consent_status",
      label: "Engineering/consent",
      questionText: "Is engineering or consent required?",
      inputType: "select",
      options: ["Not required", "Required", "Not sure"],
      required: false,
      priority: 70,
      factKey: "retaining_wall.engineering_or_consent_status",
      workAreaType: "retaining_wall",
      category: "risk",
    },
    {
      key: "retaining_wall.access",
      label: "Access",
      questionText: "How difficult is access for machinery/materials?",
      inputType: "select",
      options: ["Easy", "Moderate", "Difficult", "Not sure"],
      required: false,
      priority: 75,
      factKey: "retaining_wall.access",
      workAreaType: "retaining_wall",
      category: "risk",
    },
  ],
};
